<?php 
//error_reporting(0);
ini_set('max_execution_time', 300);

try {
/*********************** INSERT USER DATA IN TRANSACTION TABLE START ***************/


function insert_form18(
$MRH_CONSTITUTION_FORM,
$TRADE_NAME,
$PROPRIETOR_PARTNER,
$PROPRIETOR_PARTNER_NAME,

	$PROPRIETOR_NAME_1,
	$MEMBERSHIP_NUMBER_1,
	$CERTIFICATE_DATE_1,

	$PARTNER_NAME_2,
	$MEMBERSHIP_NUMBER_2,
	$CERTIFICATE_DATE_2,

	$PARTNER_NAME_3,
	$MEMBERSHIP_NUMBER_3,
	$CERTIFICATE_DATE_3,

	$PARTNER_NAME_4,
	$MEMBERSHIP_NUMBER_4,
	$CERTIFICATE_DATE_4,

	$PARTNER_NAME_5,
	$MEMBERSHIP_NUMBER_5,
	$CERTIFICATE_DATE_5,

	$PARTNER_NAME_6,
	$MEMBERSHIP_NUMBER_6,
	$CERTIFICATE_DATE_6,


$FORMATION_PROPRIETORY_DATE,
$PRESENT_PARTNERSHIP_DATE,
$PARTNERSHIP_STATUS,
$PARTNER_SHARE_STATUS,


$DATE_PARTICULARS_APPROVAL,
$FIRM_NAME,


$ADD_HEAD_OFFICE_LINE_1,
$ADD_HEAD_OFFICE_LINE_2,
$ADD_HEAD_OFFICE_LINE_3,
$ADD_HEAD_OFFICE_LINE_4,
$HEAD_OFFICE_CITY_CODE,
$HEAD_OFFICE_STATE_CODE,
$HEAD_OFFICE_ZIP_POSTAL_CODE,
$HEAD_OFFICE_TEL,
$HEAD_OFFICE_COU_CODE,
$HEAD_OFFICE_EMAIL,
$HEAD_OFFICE_MOBILE,


$SIX_MRH_RES_ADDR_LINE_1,
$SIX_MRH_RES_ADDR_LINE_2,
$SIX_MRH_RES_ADDR_LINE_3,
$SIX_MRH_RES_ADDR_LINE_4,
$SIX_MRH_RES_CITY_CODE,
$SIX_MRH_RES_STATE_CODE,
$SIX_MRH_RES_ZIP_POSTAL_CODE,
$SIX_MRH_RES_TEL,
$SIX_MRH_RES_COU_CODE,
$SIX_MRH_RES_EMAIL,
$SIX_MRH_RES_MOBILE,


$SIX_TWO_MRH_RES_ADDR_LINE_1,
$SIX_TWO_MRH_RES_ADDR_LINE_2,
$SIX_TWO_MRH_RES_ADDR_LINE_3,
$SIX_TWO_MRH_RES_ADDR_LINE_4,
$SIX_TWO_MRH_RES_CITY_CODE,
$SIX_TWO_MRH_RES_STATE_CODE,
$SIX_TWO_MRH_RES_ZIP_POSTAL_CODE,
$SIX_TWO_MRH_RES_TEL,
$SIX_TWO_MRH_RES_COU_CODE,
$SIX_TWO_MRH_RES_EMAIL,
$SIX_TWO_MRH_RES_MOBILE,


$SIX_THREE_MRH_RES_ADDR_LINE_1,
$SIX_THREE_MRH_RES_ADDR_LINE_2,
$SIX_THREE_MRH_RES_ADDR_LINE_3,
$SIX_THREE_MRH_RES_ADDR_LINE_4,
$SIX_THREE_MRH_RES_CITY_CODE,
$SIX_THREE_MRH_RES_STATE_CODE,
$SIX_THREE_MRH_RES_ZIP_POSTAL_CODE,
$SIX_THREE_MRH_RES_TEL,
$SIX_THREE_MRH_RES_COU_CODE,
$SIX_THREE_MRH_RES_EMAIL,
$SIX_THREE_MRH_RES_MOBILE,


$PLACE_OF_BRANCH_1,
$DATE_OF_BRANCH_1,
$PLACE_OF_BRANCH_2,
$DATE_OF_BRANCH_2,
$PLACE_OF_BRANCH_3,
$DATE_OF_BRANCH_3,
$PLACE_OF_BRANCH_4,
$DATE_OF_BRANCH_4,
$PLACE_OF_BRANCH_5,
$DATE_OF_BRANCH_5,


$BRANCH_OFFICE,
$MEMBER_IN_CHARGE,
$MEMBER_NUMBER,
$BRANCH_OFFICE_1,
$MEMBER_IN_CHARGE_1,
$MEMBER_NUMBER_1,
$BRANCH_OFFICE_2,
$MEMBER_IN_CHARGE_2,
$MEMBER_NUMBER_2,
$BRANCH_OFFICE_3,
$MEMBER_IN_CHARGE_3,
$MEMBER_NUMBER_3,
$BRANCH_OFFICE_4,
$MEMBER_IN_CHARGE_4,
$MEMBER_NUMBER_4,


$MRH_PRO_PARTNER,



$PAR_PRO_PA_NAME,
$CA_FIRM_NAME,
$CAPACITY_CONNECTED,
$OCCUPATION_DETAILS,


$PAR_PRO_PA_NAME_1,
$CA_FIRM_NAME_1,
$CAPACITY_CONNECTED_1,
$OCCUPATION_DETAILS_1,


$PAR_PRO_PA_NAME_2,
$CA_FIRM_NAME_2,
$CAPACITY_CONNECTED_2,
$OCCUPATION_DETAILS_2,


$PAR_PRO_PA_NAME_3,
$CA_FIRM_NAME_3,
$CAPACITY_CONNECTED_3,
$OCCUPATION_DETAILS_3,

$FIRM_IND_PAR_NAME,


$FIRM_MEM_NAME_LINE_1,
$FIRM_MEMBERSHIP_NUMBER_LINE_1,


$FIRM_MEM_NAME_LINE_2,
$FIRM_MEMBERSHIP_NUMBER_LINE_2,


$FIRM_MEM_NAME_LINE_3,
$FIRM_MEMBERSHIP_NUMBER_LINE_3,


$FIRM_MEM_NAME_LINE_4,
$FIRM_MEMBERSHIP_NUMBER_LINE_4,


$FIRM_MEM_NAME_LINE_5,
$FIRM_MEMBERSHIP_NUMBER_LINE_5,



$INS_MEM_NAME_LINE_1,
$INS_MEM_NUMBER_LINE_1 ,
$INS_MEM_DOJ_LINE_1,


$INS_MEM_NAME_LINE_2,
$INS_MEM_NUMBER_LINE_2,
$INS_MEM_DOJ_LINE_2,


$INS_MEM_NAME_LINE_3,
$INS_MEM_NUMBER_LINE_3,
$INS_MEM_DOJ_LINE_3,


$INS_MEM_NAME_LINE_4,
$INS_MEM_NUMBER_LINE_4,
$INS_MEM_DOJ_LINE_4,


$INS_MEM_NAME_LINE_5,
$INS_MEM_NUMBER_LINE_5,
$INS_MEM_DOJ_LINE_5,


$PAID_ASSISTANT,


$PAID_ASSISTANCE_NAME_LINE_1,
$ENGAGED_PAR_PRO_PA_NAME_LINE_1,
$ENGAGED_CAP_CONN_LINE_1,


$PAID_ASSISTANCE_NAME_LINE_2,
$ENGAGED_PAR_PRO_PA_NAME_LINE_2,
$ENGAGED_CAP_CONN_LINE_2,


$PAID_ASSISTANCE_NAME_LINE_3,
$ENGAGED_PAR_PRO_PA_NAME_LINE_3,
$ENGAGED_CAP_CONN_LINE_3,


$PAID_ASSISTANCE_STATUS,


$INDIVISUAL_PA_NAME_LINE_1,
$INDIVISUAL_PA_MEM_NO_LINE_1,


$INDIVISUAL_PA_NAME_LINE_2,
$INDIVISUAL_PA_MEM_NO_LINE_2,


$INDIVISUAL_PA_NAME_LINE_3,
$INDIVISUAL_PA_MEM_NO_LINE_3,


$INDIVISUAL_PA_NAME_LINE_4,
$INDIVISUAL_PA_MEM_NO_LINE_4,


   $INDIVISUAL_PA_MEM_DATE,
   $INDIVISUAL_PA_MEM_PLACE,



$SIGNATURE_MM_NUMBER_1,
$SIGNATURE_MM_NUMBER_2,
$SIGNATURE_MM_NUMBER_3,
$SIGNATURE_MM_NUMBER_4,
$SIGNATURE_MM_NUMBER_5,
$SIGNATURE_MM_NUMBER_6,



$MRH_MRN,
$FORM_NO,
$FORM_SAVE_STATUS,
$DELAY_FEE,
$TOTAL_AMT
){
	
global $conn2;	

//$STUD_REGION_CODE = get_stud_region($MRH_MRN);


$stmt = $conn2->prepare("INSERT t_form_18 SET 
MRH_CONSTITUTION_FORM = :MRH_CONSTITUTION_FORM,
TRADE_NAME = :TRADE_NAME,
PROPRIETOR_PARTNER = :PROPRIETOR_PARTNER,
PROPRIETOR_PARTNER_NAME = :PROPRIETOR_PARTNER_NAME,
PROPRIETOR_NAME_1 = :PROPRIETOR_NAME_1,
MEMBERSHIP_NUMBER_1 = :MEMBERSHIP_NUMBER_1,
CERTIFICATE_DATE_1 = :CERTIFICATE_DATE_1,
PARTNER_NAME_2 = :PARTNER_NAME_2,
MEMBERSHIP_NUMBER_2 = :MEMBERSHIP_NUMBER_2,
CERTIFICATE_DATE_2 = :CERTIFICATE_DATE_2,
PARTNER_NAME_3 = :PARTNER_NAME_3,
MEMBERSHIP_NUMBER_3 = :MEMBERSHIP_NUMBER_3,
CERTIFICATE_DATE_3 = :CERTIFICATE_DATE_3,
PARTNER_NAME_4 = :PARTNER_NAME_4,
MEMBERSHIP_NUMBER_4 = :MEMBERSHIP_NUMBER_4,
CERTIFICATE_DATE_4 = :CERTIFICATE_DATE_4,
PARTNER_NAME_5 = :PARTNER_NAME_5,
MEMBERSHIP_NUMBER_5 = :MEMBERSHIP_NUMBER_5,
CERTIFICATE_DATE_5 = :CERTIFICATE_DATE_5,
PARTNER_NAME_6 = :PARTNER_NAME_6,
MEMBERSHIP_NUMBER_6 = :MEMBERSHIP_NUMBER_6,
CERTIFICATE_DATE_6 = :CERTIFICATE_DATE_6,
FORMATION_PROPRIETORY_DATE = :FORMATION_PROPRIETORY_DATE,
PRESENT_PARTNERSHIP_DATE = :PRESENT_PARTNERSHIP_DATE,
PARTNERSHIP_STATUS = :PARTNERSHIP_STATUS,
PARTNER_SHARE_STATUS = :PARTNER_SHARE_STATUS,
DATE_PARTICULARS_APPROVAL = :DATE_PARTICULARS_APPROVAL,
FIRM_NAME = :FIRM_NAME,
ADD_HEAD_OFFICE_LINE_1 = :ADD_HEAD_OFFICE_LINE_1,
ADD_HEAD_OFFICE_LINE_2 = :ADD_HEAD_OFFICE_LINE_2,
ADD_HEAD_OFFICE_LINE_3 = :ADD_HEAD_OFFICE_LINE_3,
ADD_HEAD_OFFICE_LINE_4 = :ADD_HEAD_OFFICE_LINE_4,
HEAD_OFFICE_CITY_CODE = :HEAD_OFFICE_CITY_CODE,
HEAD_OFFICE_STATE_CODE = :HEAD_OFFICE_STATE_CODE,
HEAD_OFFICE_ZIP_POSTAL_CODE = :HEAD_OFFICE_ZIP_POSTAL_CODE,
HEAD_OFFICE_TEL = :HEAD_OFFICE_TEL,
HEAD_OFFICE_COU_CODE = :HEAD_OFFICE_COU_CODE,
HEAD_OFFICE_EMAIL = :HEAD_OFFICE_EMAIL,
HEAD_OFFICE_MOBILE = :HEAD_OFFICE_MOBILE,
SIX_MRH_RES_ADDR_LINE_1 = :SIX_MRH_RES_ADDR_LINE_1,
SIX_MRH_RES_ADDR_LINE_2 = :SIX_MRH_RES_ADDR_LINE_2,
SIX_MRH_RES_ADDR_LINE_3 = :SIX_MRH_RES_ADDR_LINE_3,
SIX_MRH_RES_ADDR_LINE_4 = :SIX_MRH_RES_ADDR_LINE_4,
SIX_MRH_RES_CITY_CODE = :SIX_MRH_RES_CITY_CODE,
SIX_MRH_RES_STATE_CODE = :SIX_MRH_RES_STATE_CODE,
SIX_MRH_RES_ZIP_POSTAL_CODE = :SIX_MRH_RES_ZIP_POSTAL_CODE,
SIX_MRH_RES_TEL = :SIX_MRH_RES_TEL,
SIX_MRH_RES_COU_CODE = :SIX_MRH_RES_COU_CODE,
SIX_MRH_RES_EMAIL = :SIX_MRH_RES_EMAIL,
SIX_MRH_RES_MOBILE = :SIX_MRH_RES_MOBILE,
SIX_TWO_MRH_RES_ADDR_LINE_1 = :SIX_TWO_MRH_RES_ADDR_LINE_1,
SIX_TWO_MRH_RES_ADDR_LINE_2 = :SIX_TWO_MRH_RES_ADDR_LINE_2,
SIX_TWO_MRH_RES_ADDR_LINE_3 = :SIX_TWO_MRH_RES_ADDR_LINE_3,
SIX_TWO_MRH_RES_ADDR_LINE_4 = :SIX_TWO_MRH_RES_ADDR_LINE_4,
SIX_TWO_MRH_RES_CITY_CODE = :SIX_TWO_MRH_RES_CITY_CODE,
SIX_TWO_MRH_RES_STATE_CODE = :SIX_TWO_MRH_RES_STATE_CODE,
SIX_TWO_MRH_RES_ZIP_POSTAL_CODE = :SIX_TWO_MRH_RES_ZIP_POSTAL_CODE,
SIX_TWO_MRH_RES_TEL = :SIX_TWO_MRH_RES_TEL,
SIX_TWO_MRH_RES_COU_CODE = :SIX_TWO_MRH_RES_COU_CODE,
SIX_TWO_MRH_RES_EMAIL = :SIX_TWO_MRH_RES_EMAIL,
SIX_TWO_MRH_RES_MOBILE = :SIX_TWO_MRH_RES_MOBILE,
SIX_THREE_MRH_RES_ADDR_LINE_1 = :SIX_THREE_MRH_RES_ADDR_LINE_1,
SIX_THREE_MRH_RES_ADDR_LINE_2 = :SIX_THREE_MRH_RES_ADDR_LINE_2,
SIX_THREE_MRH_RES_ADDR_LINE_3 = :SIX_THREE_MRH_RES_ADDR_LINE_3,
SIX_THREE_MRH_RES_ADDR_LINE_4 = :SIX_THREE_MRH_RES_ADDR_LINE_4,
SIX_THREE_MRH_RES_CITY_CODE = :SIX_THREE_MRH_RES_CITY_CODE,
SIX_THREE_MRH_RES_STATE_CODE = :SIX_THREE_MRH_RES_STATE_CODE,
SIX_THREE_MRH_RES_ZIP_POSTAL_CODE = :SIX_THREE_MRH_RES_ZIP_POSTAL_CODE,
SIX_THREE_MRH_RES_TEL = :SIX_THREE_MRH_RES_TEL,
SIX_THREE_MRH_RES_COU_CODE = :SIX_THREE_MRH_RES_COU_CODE,
SIX_THREE_MRH_RES_EMAIL = :SIX_THREE_MRH_RES_EMAIL,
SIX_THREE_MRH_RES_MOBILE = :SIX_THREE_MRH_RES_MOBILE,
PLACE_OF_BRANCH_1 = :PLACE_OF_BRANCH_1,
DATE_OF_BRANCH_1 = :DATE_OF_BRANCH_1,
PLACE_OF_BRANCH_2 = :PLACE_OF_BRANCH_2,
DATE_OF_BRANCH_2 = :DATE_OF_BRANCH_2,
PLACE_OF_BRANCH_3 = :PLACE_OF_BRANCH_3,
DATE_OF_BRANCH_3 = :DATE_OF_BRANCH_3,
PLACE_OF_BRANCH_4 = :PLACE_OF_BRANCH_4,
DATE_OF_BRANCH_4 = :DATE_OF_BRANCH_4,
PLACE_OF_BRANCH_5 = :PLACE_OF_BRANCH_5,
DATE_OF_BRANCH_5 = :DATE_OF_BRANCH_5,
BRANCH_OFFICE = :BRANCH_OFFICE,
MEMBER_IN_CHARGE = :MEMBER_IN_CHARGE,
MEMBER_NUMBER = :MEMBER_NUMBER,
BRANCH_OFFICE_1 = :BRANCH_OFFICE_1,
MEMBER_IN_CHARGE_1 = :MEMBER_IN_CHARGE_1,
MEMBER_NUMBER_1 = :MEMBER_NUMBER_1,
BRANCH_OFFICE_2 = :BRANCH_OFFICE_2,
MEMBER_IN_CHARGE_2 = :MEMBER_IN_CHARGE_2,
MEMBER_NUMBER_2 = :MEMBER_NUMBER_2,
BRANCH_OFFICE_3 = :BRANCH_OFFICE_3,
MEMBER_IN_CHARGE_3 = :MEMBER_IN_CHARGE_3,
MEMBER_NUMBER_3 = :MEMBER_NUMBER_3,
BRANCH_OFFICE_4 = :BRANCH_OFFICE_4,
MEMBER_IN_CHARGE_4 = :MEMBER_IN_CHARGE_4,
MEMBER_NUMBER_4 = :MEMBER_NUMBER_4,
MRH_PRO_PARTNER = :MRH_PRO_PARTNER,
PAR_PRO_PA_NAME = :PAR_PRO_PA_NAME,
CA_FIRM_NAME = :CA_FIRM_NAME,
CAPACITY_CONNECTED = :CAPACITY_CONNECTED,
OCCUPATION_DETAILS = :OCCUPATION_DETAILS,
PAR_PRO_PA_NAME_1 = :PAR_PRO_PA_NAME_1,
CA_FIRM_NAME_1 = :CA_FIRM_NAME_1,
CAPACITY_CONNECTED_1 = :CAPACITY_CONNECTED_1,
OCCUPATION_DETAILS_1 = :OCCUPATION_DETAILS_1,
PAR_PRO_PA_NAME_2 = :PAR_PRO_PA_NAME_2,
CA_FIRM_NAME_2 = :CA_FIRM_NAME_2,
CAPACITY_CONNECTED_2 = :CAPACITY_CONNECTED_2,
OCCUPATION_DETAILS_2 = :OCCUPATION_DETAILS_2,
PAR_PRO_PA_NAME_3 = :PAR_PRO_PA_NAME_3,
CA_FIRM_NAME_3 = :CA_FIRM_NAME_3,
CAPACITY_CONNECTED_3 = :CAPACITY_CONNECTED_3,
OCCUPATION_DETAILS_3 = :OCCUPATION_DETAILS_3,
FIRM_IND_PAR_NAME = :FIRM_IND_PAR_NAME,
FIRM_MEM_NAME_LINE_1 = :FIRM_MEM_NAME_LINE_1,
FIRM_MEMBERSHIP_NUMBER_LINE_1 = :FIRM_MEMBERSHIP_NUMBER_LINE_1,
FIRM_MEM_NAME_LINE_2 = :FIRM_MEM_NAME_LINE_2,
FIRM_MEMBERSHIP_NUMBER_LINE_2 = :FIRM_MEMBERSHIP_NUMBER_LINE_2,
FIRM_MEM_NAME_LINE_3 = :FIRM_MEM_NAME_LINE_3,
FIRM_MEMBERSHIP_NUMBER_LINE_3 = :FIRM_MEMBERSHIP_NUMBER_LINE_3,
FIRM_MEM_NAME_LINE_4 = :FIRM_MEM_NAME_LINE_4,
FIRM_MEMBERSHIP_NUMBER_LINE_4 = :FIRM_MEMBERSHIP_NUMBER_LINE_4,
FIRM_MEM_NAME_LINE_5 = :FIRM_MEM_NAME_LINE_5,
FIRM_MEMBERSHIP_NUMBER_LINE_5 = :FIRM_MEMBERSHIP_NUMBER_LINE_5,
INS_MEM_NAME_LINE_1 = :INS_MEM_NAME_LINE_1,
INS_MEM_NUMBER_LINE_1 = :INS_MEM_NUMBER_LINE_1,
INS_MEM_DOJ_LINE_1 = :INS_MEM_DOJ_LINE_1,
INS_MEM_NAME_LINE_2 = :INS_MEM_NAME_LINE_2,
INS_MEM_NUMBER_LINE_2 = :INS_MEM_NUMBER_LINE_2,
INS_MEM_DOJ_LINE_2 = :INS_MEM_DOJ_LINE_2,
INS_MEM_NAME_LINE_3 = :INS_MEM_NAME_LINE_3,
INS_MEM_NUMBER_LINE_3 = :INS_MEM_NUMBER_LINE_3,
INS_MEM_DOJ_LINE_3 = :INS_MEM_DOJ_LINE_3,
INS_MEM_NAME_LINE_4 = :INS_MEM_NAME_LINE_4,
INS_MEM_NUMBER_LINE_4 = :INS_MEM_NUMBER_LINE_4,
INS_MEM_DOJ_LINE_4 = :INS_MEM_DOJ_LINE_4,
INS_MEM_NAME_LINE_5 = :INS_MEM_NAME_LINE_5,
INS_MEM_NUMBER_LINE_5 = :INS_MEM_NUMBER_LINE_5,
INS_MEM_DOJ_LINE_5 = :INS_MEM_DOJ_LINE_5,
PAID_ASSISTANT = :PAID_ASSISTANT,
PAID_ASSISTANCE_NAME_LINE_1 = :PAID_ASSISTANCE_NAME_LINE_1,
ENGAGED_PAR_PRO_PA_NAME_LINE_1 = :ENGAGED_PAR_PRO_PA_NAME_LINE_1,
ENGAGED_CAP_CONN_LINE_1 = :ENGAGED_CAP_CONN_LINE_1,
PAID_ASSISTANCE_NAME_LINE_2 = :PAID_ASSISTANCE_NAME_LINE_2,
ENGAGED_PAR_PRO_PA_NAME_LINE_2 = :ENGAGED_PAR_PRO_PA_NAME_LINE_2,
ENGAGED_CAP_CONN_LINE_2 = :ENGAGED_CAP_CONN_LINE_2,
PAID_ASSISTANCE_NAME_LINE_3 = :PAID_ASSISTANCE_NAME_LINE_3,
ENGAGED_PAR_PRO_PA_NAME_LINE_3 = :ENGAGED_PAR_PRO_PA_NAME_LINE_3,
ENGAGED_CAP_CONN_LINE_3 = :ENGAGED_CAP_CONN_LINE_3,
PAID_ASSISTANCE_STATUS = :PAID_ASSISTANCE_STATUS,
INDIVISUAL_PA_NAME_LINE_1 = :INDIVISUAL_PA_NAME_LINE_1,
INDIVISUAL_PA_MEM_NO_LINE_1 = :INDIVISUAL_PA_MEM_NO_LINE_1,
INDIVISUAL_PA_NAME_LINE_2 = :INDIVISUAL_PA_NAME_LINE_2,
INDIVISUAL_PA_MEM_NO_LINE_2 = :INDIVISUAL_PA_MEM_NO_LINE_2,
INDIVISUAL_PA_NAME_LINE_3 = :INDIVISUAL_PA_NAME_LINE_3,
INDIVISUAL_PA_MEM_NO_LINE_3 = :INDIVISUAL_PA_MEM_NO_LINE_3,
INDIVISUAL_PA_NAME_LINE_4 = :INDIVISUAL_PA_NAME_LINE_4,
INDIVISUAL_PA_MEM_NO_LINE_4 = :INDIVISUAL_PA_MEM_NO_LINE_4,
INDIVISUAL_PA_MEM_DATE = :INDIVISUAL_PA_MEM_DATE,
INDIVISUAL_PA_MEM_PLACE = :INDIVISUAL_PA_MEM_PLACE,
SIGNATURE_MM_NUMBER_1 = :SIGNATURE_MM_NUMBER_1,
SIGNATURE_MM_NUMBER_2 = :SIGNATURE_MM_NUMBER_2,
SIGNATURE_MM_NUMBER_3 = :SIGNATURE_MM_NUMBER_3,
SIGNATURE_MM_NUMBER_4 = :SIGNATURE_MM_NUMBER_4,
SIGNATURE_MM_NUMBER_5 = :SIGNATURE_MM_NUMBER_5,
SIGNATURE_MM_NUMBER_6 = :SIGNATURE_MM_NUMBER_6,





MRH_MRN = :MRH_MRN,
FORM_SAVE_STATUS = :FORM_SAVE_STATUS,
DELAY_FEE = :DELAY_FEE,
TOTAL_AMT = :TOTAL_AMT
");

//$stmt->bindValue(':STUD_PART1_MEMBER_NO', $STUD_PART1_MEMBER_NO);
$stmt->bindValue(':MRH_CONSTITUTION_FORM', $MRH_CONSTITUTION_FORM);
$stmt->bindValue(':TRADE_NAME', $TRADE_NAME);
$stmt->bindValue(':PROPRIETOR_PARTNER', $PROPRIETOR_PARTNER);
$stmt->bindValue(':PROPRIETOR_PARTNER_NAME', $PROPRIETOR_PARTNER_NAME);
$stmt->bindValue(':PROPRIETOR_NAME_1', $PROPRIETOR_NAME_1);
$stmt->bindValue(':MEMBERSHIP_NUMBER_1', $MEMBERSHIP_NUMBER_1);
$stmt->bindValue(':CERTIFICATE_DATE_1', $CERTIFICATE_DATE_1);
$stmt->bindValue(':PARTNER_NAME_2', $PARTNER_NAME_2);
$stmt->bindValue(':MEMBERSHIP_NUMBER_2', $MEMBERSHIP_NUMBER_2);
$stmt->bindValue(':CERTIFICATE_DATE_2', $CERTIFICATE_DATE_2);
$stmt->bindValue(':PARTNER_NAME_3', $PARTNER_NAME_3);
$stmt->bindValue(':MEMBERSHIP_NUMBER_3', $MEMBERSHIP_NUMBER_3);
$stmt->bindValue(':CERTIFICATE_DATE_3', $CERTIFICATE_DATE_3);
$stmt->bindValue(':PARTNER_NAME_4', $PARTNER_NAME_4);
$stmt->bindValue(':MEMBERSHIP_NUMBER_4', $MEMBERSHIP_NUMBER_4);
$stmt->bindValue(':CERTIFICATE_DATE_4', $CERTIFICATE_DATE_4);
$stmt->bindValue(':PARTNER_NAME_5', $PARTNER_NAME_5);
$stmt->bindValue(':MEMBERSHIP_NUMBER_5', $MEMBERSHIP_NUMBER_5);
$stmt->bindValue(':CERTIFICATE_DATE_5', $CERTIFICATE_DATE_5);
$stmt->bindValue(':PARTNER_NAME_6', $PARTNER_NAME_6);
$stmt->bindValue(':MEMBERSHIP_NUMBER_6', $MEMBERSHIP_NUMBER_6);
$stmt->bindValue(':CERTIFICATE_DATE_6', $CERTIFICATE_DATE_6);
$stmt->bindValue(':FORMATION_PROPRIETORY_DATE', $FORMATION_PROPRIETORY_DATE);
$stmt->bindValue(':PRESENT_PARTNERSHIP_DATE', $PRESENT_PARTNERSHIP_DATE);
$stmt->bindValue(':PARTNERSHIP_STATUS', $PARTNERSHIP_STATUS);
$stmt->bindValue(':PARTNER_SHARE_STATUS', $PARTNER_SHARE_STATUS);
$stmt->bindValue(':DATE_PARTICULARS_APPROVAL', $DATE_PARTICULARS_APPROVAL);
$stmt->bindValue(':FIRM_NAME', $FIRM_NAME);
$stmt->bindValue(':ADD_HEAD_OFFICE_LINE_1', $ADD_HEAD_OFFICE_LINE_1);
$stmt->bindValue(':ADD_HEAD_OFFICE_LINE_2', $ADD_HEAD_OFFICE_LINE_2);
$stmt->bindValue(':ADD_HEAD_OFFICE_LINE_3', $ADD_HEAD_OFFICE_LINE_3);
$stmt->bindValue(':ADD_HEAD_OFFICE_LINE_4', $ADD_HEAD_OFFICE_LINE_4);
$stmt->bindValue(':HEAD_OFFICE_CITY_CODE', $HEAD_OFFICE_CITY_CODE);
$stmt->bindValue(':HEAD_OFFICE_STATE_CODE', $HEAD_OFFICE_STATE_CODE);
$stmt->bindValue(':HEAD_OFFICE_ZIP_POSTAL_CODE', $HEAD_OFFICE_ZIP_POSTAL_CODE);
$stmt->bindValue(':HEAD_OFFICE_TEL', $HEAD_OFFICE_TEL);
$stmt->bindValue(':HEAD_OFFICE_COU_CODE', $HEAD_OFFICE_COU_CODE);
$stmt->bindValue(':HEAD_OFFICE_EMAIL', $HEAD_OFFICE_EMAIL);
$stmt->bindValue(':HEAD_OFFICE_MOBILE', $HEAD_OFFICE_MOBILE);
$stmt->bindValue(':SIX_MRH_RES_ADDR_LINE_1', $SIX_MRH_RES_ADDR_LINE_1);
$stmt->bindValue(':SIX_MRH_RES_ADDR_LINE_2', $SIX_MRH_RES_ADDR_LINE_2);
$stmt->bindValue(':SIX_MRH_RES_ADDR_LINE_3', $SIX_MRH_RES_ADDR_LINE_3);
$stmt->bindValue(':SIX_MRH_RES_ADDR_LINE_4', $SIX_MRH_RES_ADDR_LINE_4);
$stmt->bindValue(':SIX_MRH_RES_CITY_CODE', $SIX_MRH_RES_CITY_CODE);
$stmt->bindValue(':SIX_MRH_RES_STATE_CODE', $SIX_MRH_RES_STATE_CODE);
$stmt->bindValue(':SIX_MRH_RES_ZIP_POSTAL_CODE', $SIX_MRH_RES_ZIP_POSTAL_CODE);
$stmt->bindValue(':SIX_MRH_RES_TEL', $SIX_MRH_RES_TEL);
$stmt->bindValue(':SIX_MRH_RES_COU_CODE', $SIX_MRH_RES_COU_CODE);
$stmt->bindValue(':SIX_MRH_RES_EMAIL', $SIX_MRH_RES_EMAIL);
$stmt->bindValue(':SIX_MRH_RES_MOBILE', $SIX_MRH_RES_MOBILE);
$stmt->bindValue(':SIX_TWO_MRH_RES_ADDR_LINE_1', $SIX_TWO_MRH_RES_ADDR_LINE_1);
$stmt->bindValue(':SIX_TWO_MRH_RES_ADDR_LINE_2', $SIX_TWO_MRH_RES_ADDR_LINE_2);
$stmt->bindValue(':SIX_TWO_MRH_RES_ADDR_LINE_3', $SIX_TWO_MRH_RES_ADDR_LINE_3);
$stmt->bindValue(':SIX_TWO_MRH_RES_ADDR_LINE_4', $SIX_TWO_MRH_RES_ADDR_LINE_4);
$stmt->bindValue(':SIX_TWO_MRH_RES_CITY_CODE', $SIX_TWO_MRH_RES_CITY_CODE);
$stmt->bindValue(':SIX_TWO_MRH_RES_STATE_CODE', $SIX_TWO_MRH_RES_STATE_CODE);
$stmt->bindValue(':SIX_TWO_MRH_RES_ZIP_POSTAL_CODE', $SIX_TWO_MRH_RES_ZIP_POSTAL_CODE);
$stmt->bindValue(':SIX_TWO_MRH_RES_TEL', $SIX_TWO_MRH_RES_TEL);
$stmt->bindValue(':SIX_TWO_MRH_RES_COU_CODE', $SIX_TWO_MRH_RES_COU_CODE);
$stmt->bindValue(':SIX_TWO_MRH_RES_EMAIL', $SIX_TWO_MRH_RES_EMAIL);
$stmt->bindValue(':SIX_TWO_MRH_RES_MOBILE', $SIX_TWO_MRH_RES_MOBILE);
$stmt->bindValue(':SIX_THREE_MRH_RES_ADDR_LINE_1', $SIX_THREE_MRH_RES_ADDR_LINE_1);
$stmt->bindValue(':SIX_THREE_MRH_RES_ADDR_LINE_2', $SIX_THREE_MRH_RES_ADDR_LINE_2);
$stmt->bindValue(':SIX_THREE_MRH_RES_ADDR_LINE_3', $SIX_THREE_MRH_RES_ADDR_LINE_3);
$stmt->bindValue(':SIX_THREE_MRH_RES_ADDR_LINE_4', $SIX_THREE_MRH_RES_ADDR_LINE_4);
$stmt->bindValue(':SIX_THREE_MRH_RES_CITY_CODE', $SIX_THREE_MRH_RES_CITY_CODE);
$stmt->bindValue(':SIX_THREE_MRH_RES_STATE_CODE', $SIX_THREE_MRH_RES_STATE_CODE);
$stmt->bindValue(':SIX_THREE_MRH_RES_ZIP_POSTAL_CODE', $SIX_THREE_MRH_RES_ZIP_POSTAL_CODE);
$stmt->bindValue(':SIX_THREE_MRH_RES_TEL', $SIX_THREE_MRH_RES_TEL);
$stmt->bindValue(':SIX_THREE_MRH_RES_COU_CODE', $SIX_THREE_MRH_RES_COU_CODE);
$stmt->bindValue(':SIX_THREE_MRH_RES_EMAIL', $SIX_THREE_MRH_RES_EMAIL);
$stmt->bindValue(':SIX_THREE_MRH_RES_MOBILE', $SIX_THREE_MRH_RES_MOBILE);
$stmt->bindValue(':PLACE_OF_BRANCH_1', $PLACE_OF_BRANCH_1);
$stmt->bindValue(':DATE_OF_BRANCH_1', $DATE_OF_BRANCH_1);
$stmt->bindValue(':PLACE_OF_BRANCH_2', $PLACE_OF_BRANCH_2);
$stmt->bindValue(':DATE_OF_BRANCH_2', $DATE_OF_BRANCH_2);
$stmt->bindValue(':PLACE_OF_BRANCH_3', $PLACE_OF_BRANCH_3);
$stmt->bindValue(':DATE_OF_BRANCH_3', $DATE_OF_BRANCH_3);
$stmt->bindValue(':PLACE_OF_BRANCH_4', $PLACE_OF_BRANCH_4);
$stmt->bindValue(':DATE_OF_BRANCH_4', $DATE_OF_BRANCH_4);
$stmt->bindValue(':PLACE_OF_BRANCH_5', $PLACE_OF_BRANCH_5);
$stmt->bindValue(':DATE_OF_BRANCH_5', $DATE_OF_BRANCH_5);
$stmt->bindValue(':BRANCH_OFFICE', $BRANCH_OFFICE);
$stmt->bindValue(':MEMBER_IN_CHARGE', $MEMBER_IN_CHARGE);
$stmt->bindValue(':MEMBER_NUMBER', $MEMBER_NUMBER);
$stmt->bindValue(':BRANCH_OFFICE_1', $BRANCH_OFFICE_1);
$stmt->bindValue(':MEMBER_IN_CHARGE_1', $MEMBER_IN_CHARGE_1);
$stmt->bindValue(':MEMBER_NUMBER_1', $MEMBER_NUMBER_1);
$stmt->bindValue(':BRANCH_OFFICE_2', $BRANCH_OFFICE_2);
$stmt->bindValue(':MEMBER_IN_CHARGE_2', $MEMBER_IN_CHARGE_2);
$stmt->bindValue(':MEMBER_NUMBER_2', $MEMBER_NUMBER_2);
$stmt->bindValue(':BRANCH_OFFICE_3', $BRANCH_OFFICE_3);
$stmt->bindValue(':MEMBER_IN_CHARGE_3', $MEMBER_IN_CHARGE_3);
$stmt->bindValue(':MEMBER_NUMBER_3', $MEMBER_NUMBER_3);
$stmt->bindValue(':BRANCH_OFFICE_4', $BRANCH_OFFICE_4);
$stmt->bindValue(':MEMBER_IN_CHARGE_4', $MEMBER_IN_CHARGE_4);
$stmt->bindValue(':MEMBER_NUMBER_4', $MEMBER_NUMBER_4);
$stmt->bindValue(':MRH_PRO_PARTNER', $MRH_PRO_PARTNER);
$stmt->bindValue(':PAR_PRO_PA_NAME', $PAR_PRO_PA_NAME);
$stmt->bindValue(':CA_FIRM_NAME', $CA_FIRM_NAME);
$stmt->bindValue(':CAPACITY_CONNECTED', $CAPACITY_CONNECTED);
$stmt->bindValue(':OCCUPATION_DETAILS', $OCCUPATION_DETAILS);
$stmt->bindValue(':PAR_PRO_PA_NAME_1', $PAR_PRO_PA_NAME_1);
$stmt->bindValue(':CA_FIRM_NAME_1', $CA_FIRM_NAME_1);
$stmt->bindValue(':CAPACITY_CONNECTED_1', $CAPACITY_CONNECTED_1);
$stmt->bindValue(':OCCUPATION_DETAILS_1', $OCCUPATION_DETAILS_1);
$stmt->bindValue(':PAR_PRO_PA_NAME_2', $PAR_PRO_PA_NAME_2);
$stmt->bindValue(':CA_FIRM_NAME_2', $CA_FIRM_NAME_2);
$stmt->bindValue(':CAPACITY_CONNECTED_2', $CAPACITY_CONNECTED_2);
$stmt->bindValue(':OCCUPATION_DETAILS_2', $OCCUPATION_DETAILS_2);
$stmt->bindValue(':PAR_PRO_PA_NAME_3', $PAR_PRO_PA_NAME_3);
$stmt->bindValue(':CA_FIRM_NAME_3', $CA_FIRM_NAME_3);
$stmt->bindValue(':CAPACITY_CONNECTED_3', $CAPACITY_CONNECTED_3);
$stmt->bindValue(':OCCUPATION_DETAILS_3', $OCCUPATION_DETAILS_3);
$stmt->bindValue(':FIRM_IND_PAR_NAME', $FIRM_IND_PAR_NAME);
$stmt->bindValue(':FIRM_MEM_NAME_LINE_1', $FIRM_MEM_NAME_LINE_1);
$stmt->bindValue(':FIRM_MEMBERSHIP_NUMBER_LINE_1', $FIRM_MEMBERSHIP_NUMBER_LINE_1);
$stmt->bindValue(':FIRM_MEM_NAME_LINE_2', $FIRM_MEM_NAME_LINE_2);
$stmt->bindValue(':FIRM_MEMBERSHIP_NUMBER_LINE_2', $FIRM_MEMBERSHIP_NUMBER_LINE_2);
$stmt->bindValue(':FIRM_MEM_NAME_LINE_3', $FIRM_MEM_NAME_LINE_3);
$stmt->bindValue(':FIRM_MEMBERSHIP_NUMBER_LINE_3', $FIRM_MEMBERSHIP_NUMBER_LINE_3);
$stmt->bindValue(':FIRM_MEM_NAME_LINE_4', $FIRM_MEM_NAME_LINE_4);
$stmt->bindValue(':FIRM_MEMBERSHIP_NUMBER_LINE_4', $FIRM_MEMBERSHIP_NUMBER_LINE_4);
$stmt->bindValue(':FIRM_MEM_NAME_LINE_5', $FIRM_MEM_NAME_LINE_5);
$stmt->bindValue(':FIRM_MEMBERSHIP_NUMBER_LINE_5', $FIRM_MEMBERSHIP_NUMBER_LINE_5);
$stmt->bindValue(':INS_MEM_NAME_LINE_1', $INS_MEM_NAME_LINE_1);
$stmt->bindValue(':INS_MEM_NUMBER_LINE_1', $INS_MEM_NUMBER_LINE_1);
$stmt->bindValue(':INS_MEM_DOJ_LINE_1', $INS_MEM_DOJ_LINE_1);
$stmt->bindValue(':INS_MEM_NAME_LINE_2', $INS_MEM_NAME_LINE_2);
$stmt->bindValue(':INS_MEM_NUMBER_LINE_2', $INS_MEM_NUMBER_LINE_2);
$stmt->bindValue(':INS_MEM_DOJ_LINE_2', $INS_MEM_DOJ_LINE_2);
$stmt->bindValue(':INS_MEM_NAME_LINE_3', $INS_MEM_NAME_LINE_3);
$stmt->bindValue(':INS_MEM_NUMBER_LINE_3', $INS_MEM_NUMBER_LINE_3);
$stmt->bindValue(':INS_MEM_DOJ_LINE_3', $INS_MEM_DOJ_LINE_3);
$stmt->bindValue(':INS_MEM_NAME_LINE_4', $INS_MEM_NAME_LINE_4);
$stmt->bindValue(':INS_MEM_NUMBER_LINE_4', $INS_MEM_NUMBER_LINE_4);
$stmt->bindValue(':INS_MEM_DOJ_LINE_4', $INS_MEM_DOJ_LINE_4);
$stmt->bindValue(':INS_MEM_NAME_LINE_5', $INS_MEM_NAME_LINE_5);
$stmt->bindValue(':INS_MEM_NUMBER_LINE_5', $INS_MEM_NUMBER_LINE_5);
$stmt->bindValue(':INS_MEM_DOJ_LINE_5', $INS_MEM_DOJ_LINE_5);
$stmt->bindValue(':PAID_ASSISTANT', $PAID_ASSISTANT);
$stmt->bindValue(':PAID_ASSISTANCE_NAME_LINE_1', $PAID_ASSISTANCE_NAME_LINE_1);
$stmt->bindValue(':ENGAGED_PAR_PRO_PA_NAME_LINE_1', $ENGAGED_PAR_PRO_PA_NAME_LINE_1);
$stmt->bindValue(':ENGAGED_CAP_CONN_LINE_1', $ENGAGED_CAP_CONN_LINE_1);
$stmt->bindValue(':PAID_ASSISTANCE_NAME_LINE_2', $PAID_ASSISTANCE_NAME_LINE_2);
$stmt->bindValue(':ENGAGED_PAR_PRO_PA_NAME_LINE_2', $ENGAGED_PAR_PRO_PA_NAME_LINE_2);
$stmt->bindValue(':ENGAGED_CAP_CONN_LINE_2', $ENGAGED_CAP_CONN_LINE_2);
$stmt->bindValue(':PAID_ASSISTANCE_NAME_LINE_3', $PAID_ASSISTANCE_NAME_LINE_3);
$stmt->bindValue(':ENGAGED_PAR_PRO_PA_NAME_LINE_3', $ENGAGED_PAR_PRO_PA_NAME_LINE_3);
$stmt->bindValue(':ENGAGED_CAP_CONN_LINE_3', $ENGAGED_CAP_CONN_LINE_3);
$stmt->bindValue(':PAID_ASSISTANCE_STATUS', $PAID_ASSISTANCE_STATUS);
$stmt->bindValue(':INDIVISUAL_PA_NAME_LINE_1', $INDIVISUAL_PA_NAME_LINE_1);
$stmt->bindValue(':INDIVISUAL_PA_MEM_NO_LINE_1', $INDIVISUAL_PA_MEM_NO_LINE_1);
$stmt->bindValue(':INDIVISUAL_PA_NAME_LINE_2', $INDIVISUAL_PA_NAME_LINE_2);
$stmt->bindValue(':INDIVISUAL_PA_MEM_NO_LINE_2', $INDIVISUAL_PA_MEM_NO_LINE_2);
$stmt->bindValue(':INDIVISUAL_PA_NAME_LINE_3', $INDIVISUAL_PA_NAME_LINE_3);
$stmt->bindValue(':INDIVISUAL_PA_MEM_NO_LINE_3', $INDIVISUAL_PA_MEM_NO_LINE_3);
$stmt->bindValue(':INDIVISUAL_PA_NAME_LINE_4', $INDIVISUAL_PA_NAME_LINE_4);
$stmt->bindValue(':INDIVISUAL_PA_MEM_NO_LINE_4', $INDIVISUAL_PA_MEM_NO_LINE_4);
$stmt->bindValue(':INDIVISUAL_PA_MEM_DATE', $INDIVISUAL_PA_MEM_DATE);
$stmt->bindValue(':INDIVISUAL_PA_MEM_PLACE', $INDIVISUAL_PA_MEM_PLACE);
$stmt->bindValue(':SIGNATURE_MM_NUMBER_1', $SIGNATURE_MM_NUMBER_1);
$stmt->bindValue(':SIGNATURE_MM_NUMBER_2', $SIGNATURE_MM_NUMBER_2);
$stmt->bindValue(':SIGNATURE_MM_NUMBER_3', $SIGNATURE_MM_NUMBER_3);
$stmt->bindValue(':SIGNATURE_MM_NUMBER_4', $SIGNATURE_MM_NUMBER_4);
$stmt->bindValue(':SIGNATURE_MM_NUMBER_5', $SIGNATURE_MM_NUMBER_5);
$stmt->bindValue(':SIGNATURE_MM_NUMBER_6', $SIGNATURE_MM_NUMBER_6);


//$stmt->bindValue(':STUD_PART1_VIDE_REGISTRATION', $STUD_PART1_VIDE_REGISTRATION);

$stmt->bindValue(':MRH_MRN', $MRH_MRN);
$stmt->bindValue(':FORM_SAVE_STATUS', $FORM_SAVE_STATUS);
$stmt->bindValue(':DELAY_FEE', $DELAY_FEE);
$stmt->bindValue(':TOTAL_AMT', $TOTAL_AMT);
/*

$stmt->bindValue(':MRH_MRN', $MRH_MRN);
$stmt->bindValue(':FORM_NO', $FORM_NO);
$stmt->bindValue(':FORM_SAVE_STATUS', $FORM_SAVE_STATUS); */
//$stmt->bindValue(':STUD_REGION_CODE', $STUD_REGION_CODE);


$res = $stmt->execute();
		//print_r($res);	
if($res === false){
	//echo "fhhhf";
	$error = $res->errorInfo();
	print_r($error);
	file_put_contents('error_log.txt', 'Date : '.date('d-m-Y h:i:s').' ::'.$error[2].' for '.$MRH_MRN.PHP_EOL, FILE_APPEND);
}else{	
//echo "tt";die;
	//print_r($res);
}
//die;
	
}
/*********************** INSERT USER DATA IN TRANSACTION TABLE END ***************/


/*********************** UPDATE USER DATA IN TRANSACTION TABLE START ***************/
function update_form18(
$MRH_CONSTITUTION_FORM,
$TRADE_NAME,

$PROPRIETOR_PARTNER,
$PROPRIETOR_PARTNER_NAME,

	$PROPRIETOR_NAME_1,
	$MEMBERSHIP_NUMBER_1,
	$CERTIFICATE_DATE_1,

	$PARTNER_NAME_2,
	$MEMBERSHIP_NUMBER_2,
	$CERTIFICATE_DATE_2,

	$PARTNER_NAME_3,
	$MEMBERSHIP_NUMBER_3,
	$CERTIFICATE_DATE_3,

	$PARTNER_NAME_4,
	$MEMBERSHIP_NUMBER_4,
	$CERTIFICATE_DATE_4,

	$PARTNER_NAME_5,
	$MEMBERSHIP_NUMBER_5,
	$CERTIFICATE_DATE_5,

	$PARTNER_NAME_6,
	$MEMBERSHIP_NUMBER_6,
	$CERTIFICATE_DATE_6,


$FORMATION_PROPRIETORY_DATE,
$PRESENT_PARTNERSHIP_DATE,
$PARTNERSHIP_STATUS,
$PARTNER_SHARE_STATUS,


$DATE_PARTICULARS_APPROVAL,
$FIRM_NAME,


$ADD_HEAD_OFFICE_LINE_1,
$ADD_HEAD_OFFICE_LINE_2,
$ADD_HEAD_OFFICE_LINE_3,
$ADD_HEAD_OFFICE_LINE_4,
$HEAD_OFFICE_CITY_CODE,
$HEAD_OFFICE_STATE_CODE,
$HEAD_OFFICE_ZIP_POSTAL_CODE,
$HEAD_OFFICE_TEL,
$HEAD_OFFICE_COU_CODE,
$HEAD_OFFICE_EMAIL,
$HEAD_OFFICE_MOBILE,


$SIX_MRH_RES_ADDR_LINE_1,
$SIX_MRH_RES_ADDR_LINE_2,
$SIX_MRH_RES_ADDR_LINE_3,
$SIX_MRH_RES_ADDR_LINE_4,
$SIX_MRH_RES_CITY_CODE,
$SIX_MRH_RES_STATE_CODE,
$SIX_MRH_RES_ZIP_POSTAL_CODE,
$SIX_MRH_RES_TEL,
$SIX_MRH_RES_COU_CODE,
$SIX_MRH_RES_EMAIL,
$SIX_MRH_RES_MOBILE,


$SIX_TWO_MRH_RES_ADDR_LINE_1,
$SIX_TWO_MRH_RES_ADDR_LINE_2,
$SIX_TWO_MRH_RES_ADDR_LINE_3,
$SIX_TWO_MRH_RES_ADDR_LINE_4,
$SIX_TWO_MRH_RES_CITY_CODE,
$SIX_TWO_MRH_RES_STATE_CODE,
$SIX_TWO_MRH_RES_ZIP_POSTAL_CODE,
$SIX_TWO_MRH_RES_TEL,
$SIX_TWO_MRH_RES_COU_CODE,
$SIX_TWO_MRH_RES_EMAIL,
$SIX_TWO_MRH_RES_MOBILE,


$SIX_THREE_MRH_RES_ADDR_LINE_1,
$SIX_THREE_MRH_RES_ADDR_LINE_2,
$SIX_THREE_MRH_RES_ADDR_LINE_3,
$SIX_THREE_MRH_RES_ADDR_LINE_4,
$SIX_THREE_MRH_RES_CITY_CODE,
$SIX_THREE_MRH_RES_STATE_CODE,
$SIX_THREE_MRH_RES_ZIP_POSTAL_CODE,
$SIX_THREE_MRH_RES_TEL,
$SIX_THREE_MRH_RES_COU_CODE,
$SIX_THREE_MRH_RES_EMAIL,
$SIX_THREE_MRH_RES_MOBILE,


$PLACE_OF_BRANCH_1,
$DATE_OF_BRANCH_1,
$PLACE_OF_BRANCH_2,
$DATE_OF_BRANCH_2,
$PLACE_OF_BRANCH_3,
$DATE_OF_BRANCH_3,
$PLACE_OF_BRANCH_4,
$DATE_OF_BRANCH_4,
$PLACE_OF_BRANCH_5,
$DATE_OF_BRANCH_5,


$BRANCH_OFFICE,
$MEMBER_IN_CHARGE,
$MEMBER_NUMBER,
$BRANCH_OFFICE_1,
$MEMBER_IN_CHARGE_1,
$MEMBER_NUMBER_1,
$BRANCH_OFFICE_2,
$MEMBER_IN_CHARGE_2,
$MEMBER_NUMBER_2,
$BRANCH_OFFICE_3,
$MEMBER_IN_CHARGE_3,
$MEMBER_NUMBER_3,
$BRANCH_OFFICE_4,
$MEMBER_IN_CHARGE_4,
$MEMBER_NUMBER_4,


$MRH_PRO_PARTNER,



$PAR_PRO_PA_NAME,
$CA_FIRM_NAME,
$CAPACITY_CONNECTED,
$OCCUPATION_DETAILS,


$PAR_PRO_PA_NAME_1,
$CA_FIRM_NAME_1,
$CAPACITY_CONNECTED_1,
$OCCUPATION_DETAILS_1,


$PAR_PRO_PA_NAME_2,
$CA_FIRM_NAME_2,
$CAPACITY_CONNECTED_2,
$OCCUPATION_DETAILS_2,


$PAR_PRO_PA_NAME_3,
$CA_FIRM_NAME_3,
$CAPACITY_CONNECTED_3,
$OCCUPATION_DETAILS_3,

$FIRM_IND_PAR_NAME,


$FIRM_MEM_NAME_LINE_1,
$FIRM_MEMBERSHIP_NUMBER_LINE_1,


$FIRM_MEM_NAME_LINE_2,
$FIRM_MEMBERSHIP_NUMBER_LINE_2,


$FIRM_MEM_NAME_LINE_3,
$FIRM_MEMBERSHIP_NUMBER_LINE_3,


$FIRM_MEM_NAME_LINE_4,
$FIRM_MEMBERSHIP_NUMBER_LINE_4,


$FIRM_MEM_NAME_LINE_5,
$FIRM_MEMBERSHIP_NUMBER_LINE_5,



$INS_MEM_NAME_LINE_1,
$INS_MEM_NUMBER_LINE_1 ,
$INS_MEM_DOJ_LINE_1,


$INS_MEM_NAME_LINE_2,
$INS_MEM_NUMBER_LINE_2,
$INS_MEM_DOJ_LINE_2,


$INS_MEM_NAME_LINE_3,
$INS_MEM_NUMBER_LINE_3,
$INS_MEM_DOJ_LINE_3,


$INS_MEM_NAME_LINE_4,
$INS_MEM_NUMBER_LINE_4,
$INS_MEM_DOJ_LINE_4,


$INS_MEM_NAME_LINE_5,
$INS_MEM_NUMBER_LINE_5,
$INS_MEM_DOJ_LINE_5,


$PAID_ASSISTANT,


$PAID_ASSISTANCE_NAME_LINE_1,
$ENGAGED_PAR_PRO_PA_NAME_LINE_1,
$ENGAGED_CAP_CONN_LINE_1,


$PAID_ASSISTANCE_NAME_LINE_2,
$ENGAGED_PAR_PRO_PA_NAME_LINE_2,
$ENGAGED_CAP_CONN_LINE_2,


$PAID_ASSISTANCE_NAME_LINE_3,
$ENGAGED_PAR_PRO_PA_NAME_LINE_3,
$ENGAGED_CAP_CONN_LINE_3,


$PAID_ASSISTANCE_STATUS,


$INDIVISUAL_PA_NAME_LINE_1,
$INDIVISUAL_PA_MEM_NO_LINE_1,


$INDIVISUAL_PA_NAME_LINE_2,
$INDIVISUAL_PA_MEM_NO_LINE_2,


$INDIVISUAL_PA_NAME_LINE_3,
$INDIVISUAL_PA_MEM_NO_LINE_3,


$INDIVISUAL_PA_NAME_LINE_4,
$INDIVISUAL_PA_MEM_NO_LINE_4,


   $INDIVISUAL_PA_MEM_DATE,
   $INDIVISUAL_PA_MEM_PLACE,



$SIGNATURE_MM_NUMBER_1,
$SIGNATURE_MM_NUMBER_2,
$SIGNATURE_MM_NUMBER_3,
$SIGNATURE_MM_NUMBER_4,
$SIGNATURE_MM_NUMBER_5,
$SIGNATURE_MM_NUMBER_6,


$MRH_MRN,
$FORM_NO,
$FORM_SAVE_STATUS,
$DELAY_FEE,
$TOTAL_AMT
){
	
global $conn2;	

$ACKR_CONTROL_MAX_NO=ACKR_ControlNo_New_18('form_109');
$TERMINATE_CONTROL_NO='ACKTER'.str_pad($ACKR_CONTROL_MAX_NO['control_no']+1, 8, "0", STR_PAD_LEFT);

if(!empty($_SERVER['HTTP_CLIENT_IP'])) {
	$User_IP = $_SERVER['HTTP_CLIENT_IP'];
}elseif(!empty($_SERVER['HTTP_X_FORWARDED_FOR'])){
	$User_IP = $_SERVER['HTTP_X_FORWARDED_FOR'];
}else{
	$User_IP = $_SERVER['REMOTE_ADDR'];
}

  /* echo "UPDATE t_form_18 SET 
TRADE_NAME = '".$TRADE_NAME."',
PROPRIETOR_PARTNER = '".$PROPRIETOR_PARTNER."',
PROPRIETOR_PARTNER_NAME = '".$PROPRIETOR_PARTNER_NAME."',
PROPRIETOR_NAME_1 = '".$PROPRIETOR_NAME_1."',
MEMBERSHIP_NUMBER_1 = '".$MEMBERSHIP_NUMBER_1."',
CERTIFICATE_DATE_1 = '".$CERTIFICATE_DATE_1."',
PARTNER_NAME_2 = '".$PARTNER_NAME_2."',
MEMBERSHIP_NUMBER_2 = '".$MEMBERSHIP_NUMBER_2."',
CERTIFICATE_DATE_2 = '".$CERTIFICATE_DATE_2."',
PARTNER_NAME_3 = '".$PARTNER_NAME_3."',
MEMBERSHIP_NUMBER_3 = '".$MEMBERSHIP_NUMBER_3."',
CERTIFICATE_DATE_3 = '".$CERTIFICATE_DATE_3."',
PARTNER_NAME_4 = '".$PARTNER_NAME_4."',
MEMBERSHIP_NUMBER_4 = '".$MEMBERSHIP_NUMBER_4."',
CERTIFICATE_DATE_4 = '".$CERTIFICATE_DATE_4."',
PARTNER_NAME_5 = '".$PARTNER_NAME_5."',
MEMBERSHIP_NUMBER_5 = '".$MEMBERSHIP_NUMBER_5."',
CERTIFICATE_DATE_5 = '".$CERTIFICATE_DATE_5."',
PARTNER_NAME_6 = '".$PARTNER_NAME_6."',
MEMBERSHIP_NUMBER_6 = '".$MEMBERSHIP_NUMBER_6."',
CERTIFICATE_DATE_6 = '".$CERTIFICATE_DATE_6."',
FORMATION_PROPRIETORY_DATE = '".$FORMATION_PROPRIETORY_DATE."',
PRESENT_PARTNERSHIP_DATE = '".$PRESENT_PARTNERSHIP_DATE."',
PARTNERSHIP_STATUS = '".$PARTNERSHIP_STATUS."',
PARTNER_SHARE_STATUS = '".$PARTNER_SHARE_STATUS."',
DATE_PARTICULARS_APPROVAL = '".$DATE_PARTICULARS_APPROVAL."',
FIRM_NAME = '".$FIRM_NAME."',
ADD_HEAD_OFFICE_LINE_1 = '".$ADD_HEAD_OFFICE_LINE_1."',
ADD_HEAD_OFFICE_LINE_2 = '".$ADD_HEAD_OFFICE_LINE_2."',
ADD_HEAD_OFFICE_LINE_3 = '".$ADD_HEAD_OFFICE_LINE_3."',
ADD_HEAD_OFFICE_LINE_4 = '".$ADD_HEAD_OFFICE_LINE_4."',
HEAD_OFFICE_CITY_CODE = '".$HEAD_OFFICE_CITY_CODE."',
HEAD_OFFICE_STATE_CODE = '".$HEAD_OFFICE_STATE_CODE."',
HEAD_OFFICE_ZIP_POSTAL_CODE = '".$HEAD_OFFICE_ZIP_POSTAL_CODE."',
HEAD_OFFICE_TEL = '".$HEAD_OFFICE_TEL."',
HEAD_OFFICE_COU_CODE = '".$HEAD_OFFICE_COU_CODE."',
HEAD_OFFICE_EMAIL = '".$HEAD_OFFICE_EMAIL."',
HEAD_OFFICE_MOBILE = '".$HEAD_OFFICE_MOBILE."',
SIX_MRH_RES_ADDR_LINE_1 = '".$SIX_MRH_RES_ADDR_LINE_1."',
SIX_MRH_RES_ADDR_LINE_2 = '".$SIX_MRH_RES_ADDR_LINE_2."',
SIX_MRH_RES_ADDR_LINE_3 = '".$SIX_MRH_RES_ADDR_LINE_3."',
SIX_MRH_RES_ADDR_LINE_4 = '".$SIX_MRH_RES_ADDR_LINE_4."',
SIX_MRH_RES_CITY_CODE = '".$SIX_MRH_RES_CITY_CODE."',
SIX_MRH_RES_STATE_CODE = '".$SIX_MRH_RES_STATE_CODE."',
SIX_MRH_RES_ZIP_POSTAL_CODE = '".$SIX_MRH_RES_ZIP_POSTAL_CODE."',
SIX_MRH_RES_TEL = '".$SIX_MRH_RES_TEL."',
SIX_MRH_RES_COU_CODE = '".$SIX_MRH_RES_COU_CODE."',
SIX_MRH_RES_EMAIL = '".$SIX_MRH_RES_EMAIL."',
SIX_MRH_RES_MOBILE = '".$SIX_MRH_RES_MOBILE."',
SIX_TWO_MRH_RES_ADDR_LINE_1 = '".$SIX_TWO_MRH_RES_ADDR_LINE_1."',
SIX_TWO_MRH_RES_ADDR_LINE_2 = '".$SIX_TWO_MRH_RES_ADDR_LINE_2."',
SIX_TWO_MRH_RES_ADDR_LINE_3 = '".$SIX_TWO_MRH_RES_ADDR_LINE_3."',
SIX_TWO_MRH_RES_ADDR_LINE_4 = '".$SIX_TWO_MRH_RES_ADDR_LINE_4."',



SIX_TWO_MRH_RES_CITY_CODE = '".$SIX_TWO_MRH_RES_CITY_CODE."',
SIX_TWO_MRH_RES_STATE_CODE = '".$SIX_TWO_MRH_RES_STATE_CODE."',
SIX_TWO_MRH_RES_ZIP_POSTAL_CODE = '".$SIX_TWO_MRH_RES_ZIP_POSTAL_CODE."',
SIX_TWO_MRH_RES_TEL = '".$SIX_TWO_MRH_RES_TEL."',
SIX_TWO_MRH_RES_COU_CODE = '".$SIX_TWO_MRH_RES_COU_CODE."',

SIX_TWO_MRH_RES_EMAIL = '".$SIX_TWO_MRH_RES_EMAIL."',
SIX_TWO_MRH_RES_MOBILE = '".$SIX_TWO_MRH_RES_MOBILE."',

SIX_THREE_MRH_RES_ADDR_LINE_1 = '".$SIX_THREE_MRH_RES_ADDR_LINE_1."',
SIX_THREE_MRH_RES_ADDR_LINE_2 = '".$SIX_THREE_MRH_RES_ADDR_LINE_2."',
SIX_THREE_MRH_RES_ADDR_LINE_3 = '".$SIX_THREE_MRH_RES_ADDR_LINE_3."',
SIX_THREE_MRH_RES_ADDR_LINE_4 = '".$SIX_THREE_MRH_RES_ADDR_LINE_4."',
SIX_THREE_MRH_RES_CITY_CODE = '".$SIX_THREE_MRH_RES_CITY_CODE."',
SIX_THREE_MRH_RES_STATE_CODE = '".$SIX_THREE_MRH_RES_STATE_CODE."',
SIX_THREE_MRH_RES_ZIP_POSTAL_CODE = '".$SIX_THREE_MRH_RES_ZIP_POSTAL_CODE."',
SIX_THREE_MRH_RES_TEL = '".$SIX_THREE_MRH_RES_TEL."',
SIX_THREE_MRH_RES_COU_CODE = '".$SIX_THREE_MRH_RES_COU_CODE."',
SIX_THREE_MRH_RES_EMAIL = '".$SIX_THREE_MRH_RES_EMAIL."',
SIX_THREE_MRH_RES_MOBILE = '".$SIX_THREE_MRH_RES_MOBILE."',

PLACE_OF_BRANCH_1 = '".$PLACE_OF_BRANCH_1."',
DATE_OF_BRANCH_1 = '".$DATE_OF_BRANCH_1."',
PLACE_OF_BRANCH_2 = '".$PLACE_OF_BRANCH_2."',
DATE_OF_BRANCH_2 = '".$DATE_OF_BRANCH_2."',
PLACE_OF_BRANCH_3 = '".$PLACE_OF_BRANCH_3."',
DATE_OF_BRANCH_3 = '".$DATE_OF_BRANCH_3."',
PLACE_OF_BRANCH_4 = '".$PLACE_OF_BRANCH_4."',
DATE_OF_BRANCH_4 = '".$DATE_OF_BRANCH_4."',
PLACE_OF_BRANCH_5 = '".$PLACE_OF_BRANCH_5."',
DATE_OF_BRANCH_5 = '".$DATE_OF_BRANCH_5."',

BRANCH_OFFICE = '".$BRANCH_OFFICE."',
MEMBER_IN_CHARGE = '".$MEMBER_IN_CHARGE."',
MEMBER_NUMBER = '".$MEMBER_NUMBER."',
BRANCH_OFFICE_1 = '".$BRANCH_OFFICE_1."',
MEMBER_IN_CHARGE_1 = '".$MEMBER_IN_CHARGE_1."',
MEMBER_NUMBER_1 = '".$MEMBER_NUMBER_1."',
BRANCH_OFFICE_2 = '".$BRANCH_OFFICE_2."',
MEMBER_IN_CHARGE_2 = '".$MEMBER_IN_CHARGE_2."',
MEMBER_NUMBER_2 = '".$MEMBER_NUMBER_2."',
BRANCH_OFFICE_3 = '".$BRANCH_OFFICE_3."',
MEMBER_IN_CHARGE_3 = '".$MEMBER_IN_CHARGE_3."',
MEMBER_NUMBER_3 = '".$MEMBER_NUMBER_3."',
BRANCH_OFFICE_4 = '".$BRANCH_OFFICE_4."',
MEMBER_IN_CHARGE_4 = '".$MEMBER_IN_CHARGE_4."',
MEMBER_NUMBER_4 = '".$MEMBER_NUMBER_4."',

MRH_PRO_PARTNER = '".$MRH_PRO_PARTNER."',
PAR_PRO_PA_NAME = '".$PAR_PRO_PA_NAME."',
CA_FIRM_NAME = '".$CA_FIRM_NAME."',
CAPACITY_CONNECTED = '".$CAPACITY_CONNECTED."',
OCCUPATION_DETAILS = '".$OCCUPATION_DETAILS."',
PAR_PRO_PA_NAME_1 = '".$PAR_PRO_PA_NAME_1."',
CA_FIRM_NAME_1 = '".$CA_FIRM_NAME_1."',
CAPACITY_CONNECTED_1 = '".$CAPACITY_CONNECTED_1."',
OCCUPATION_DETAILS_1 = '".$OCCUPATION_DETAILS_1."',
PAR_PRO_PA_NAME_2 = '".$PAR_PRO_PA_NAME_2."',
CA_FIRM_NAME_2 = '".$CA_FIRM_NAME_2."',
CAPACITY_CONNECTED_2 = '".$CAPACITY_CONNECTED_2."',
OCCUPATION_DETAILS_2 = '".$OCCUPATION_DETAILS_2."',
PAR_PRO_PA_NAME_3 = '".$PAR_PRO_PA_NAME_3."',
CA_FIRM_NAME_3 = '".$CA_FIRM_NAME_3."',
CAPACITY_CONNECTED_3 = '".$CAPACITY_CONNECTED_3."',
OCCUPATION_DETAILS_3 = '".$OCCUPATION_DETAILS_3."',

FIRM_IND_PAR_NAME = '".$FIRM_IND_PAR_NAME."',
FIRM_MEM_NAME_LINE_1 = '".$FIRM_MEM_NAME_LINE_1."',
FIRM_MEMBERSHIP_NUMBER_LINE_1 = '".$FIRM_MEMBERSHIP_NUMBER_LINE_1."',
FIRM_MEM_NAME_LINE_2 = '".$FIRM_MEM_NAME_LINE_2."',
FIRM_MEMBERSHIP_NUMBER_LINE_2 = '".$FIRM_MEMBERSHIP_NUMBER_LINE_2."',
FIRM_MEM_NAME_LINE_3 = '".$FIRM_MEM_NAME_LINE_3."',
FIRM_MEMBERSHIP_NUMBER_LINE_3 = '".$FIRM_MEMBERSHIP_NUMBER_LINE_3."',
FIRM_MEM_NAME_LINE_4 = '".$FIRM_MEM_NAME_LINE_4."',
FIRM_MEMBERSHIP_NUMBER_LINE_4 = '".$FIRM_MEMBERSHIP_NUMBER_LINE_4."',
FIRM_MEM_NAME_LINE_5 = '".$FIRM_MEM_NAME_LINE_5."',
FIRM_MEMBERSHIP_NUMBER_LINE_5 = '".$FIRM_MEMBERSHIP_NUMBER_LINE_5."',

INS_MEM_NAME_LINE_1 = '".$INS_MEM_NAME_LINE_1."',
INS_MEM_NUMBER_LINE_1 = '".$INS_MEM_NUMBER_LINE_1."',
INS_MEM_DOJ_LINE_1 = '".$INS_MEM_DOJ_LINE_1."',

INS_MEM_NAME_LINE_2 = '".$INS_MEM_NAME_LINE_2."',
INS_MEM_NUMBER_LINE_2 = '".$INS_MEM_NUMBER_LINE_2."',
INS_MEM_DOJ_LINE_2 = '".$INS_MEM_DOJ_LINE_2."',

INS_MEM_NAME_LINE_3 = '".$INS_MEM_NAME_LINE_3."',
INS_MEM_NUMBER_LINE_3 = '".$INS_MEM_NUMBER_LINE_3."',
INS_MEM_DOJ_LINE_3 = '".$INS_MEM_DOJ_LINE_3."',

INS_MEM_NAME_LINE_4 = '".$INS_MEM_NAME_LINE_4."',
INS_MEM_NUMBER_LINE_4 = '".$INS_MEM_NUMBER_LINE_4."',
INS_MEM_DOJ_LINE_4 = '".$INS_MEM_DOJ_LINE_4."',

INS_MEM_NAME_LINE_5 = '".$INS_MEM_NAME_LINE_5."',
INS_MEM_NUMBER_LINE_5 = '".$INS_MEM_NUMBER_LINE_5."',
INS_MEM_DOJ_LINE_5 = '".$INS_MEM_DOJ_LINE_5."',

PAID_ASSISTANT = '".$PAID_ASSISTANT."',

PAID_ASSISTANCE_NAME_LINE_1 = '".$PAID_ASSISTANCE_NAME_LINE_1."',
ENGAGED_PAR_PRO_PA_NAME_LINE_1 = '".$ENGAGED_PAR_PRO_PA_NAME_LINE_1."',
ENGAGED_CAP_CONN_LINE_1 = '".$STUD_PART1_TERMINATED_LEAVE."',

PAID_ASSISTANCE_NAME_LINE_2 = '".$PAID_ASSISTANCE_NAME_LINE_2."',
ENGAGED_PAR_PRO_PA_NAME_LINE_2 = '".$ENGAGED_PAR_PRO_PA_NAME_LINE_2."',
ENGAGED_CAP_CONN_LINE_2 = '".$ENGAGED_CAP_CONN_LINE_2."',

PAID_ASSISTANCE_NAME_LINE_3 = '".$PAID_ASSISTANCE_NAME_LINE_3."',
ENGAGED_PAR_PRO_PA_NAME_LINE_3 = '".$ENGAGED_PAR_PRO_PA_NAME_LINE_3."',
ENGAGED_CAP_CONN_LINE_3 = '".$ENGAGED_CAP_CONN_LINE_3."',

PAID_ASSISTANCE_STATUS = '".$PAID_ASSISTANCE_STATUS."',

INDIVISUAL_PA_NAME_LINE_1 = '".$INDIVISUAL_PA_NAME_LINE_1."',
INDIVISUAL_PA_MEM_NO_LINE_1 = '".$INDIVISUAL_PA_MEM_NO_LINE_1."',

INDIVISUAL_PA_NAME_LINE_2 = '".$INDIVISUAL_PA_NAME_LINE_2."',
INDIVISUAL_PA_MEM_NO_LINE_2 = '".$INDIVISUAL_PA_MEM_NO_LINE_2."',

INDIVISUAL_PA_NAME_LINE_3 = '".$INDIVISUAL_PA_NAME_LINE_3."',
INDIVISUAL_PA_MEM_NO_LINE_3 = '".$INDIVISUAL_PA_MEM_NO_LINE_3."',

INDIVISUAL_PA_NAME_LINE_4 = '".$INDIVISUAL_PA_NAME_LINE_4."',
INDIVISUAL_PA_MEM_NO_LINE_4 = '".$INDIVISUAL_PA_MEM_NO_LINE_4."',


INDIVISUAL_PA_MEM_DATE = '".$INDIVISUAL_PA_MEM_DATE."',
INDIVISUAL_PA_MEM_PLACE = '".$INDIVISUAL_PA_MEM_PLACE."',


SIGNATURE_MM_NUMBER_1 = '".$SIGNATURE_MM_NUMBER_1."',
SIGNATURE_MM_NUMBER_2 = '".$SIGNATURE_MM_NUMBER_2."',
SIGNATURE_MM_NUMBER_3 = '".$SIGNATURE_MM_NUMBER_3."',
SIGNATURE_MM_NUMBER_4 = '".$SIGNATURE_MM_NUMBER_4."',
SIGNATURE_MM_NUMBER_5 = '".$SIGNATURE_MM_NUMBER_5."',
SIGNATURE_MM_NUMBER_6 ='".$SIGNATURE_MM_NUMBER_6."',



MRH_MRN = '".$MRH_MRN."',
FORM_SAVE_STATUS = '".$FORM_SAVE_STATUS."',


User_IP = '".$User_IP."',
NAME_RESTORING_CONTROL_NO = '".$TERMINATE_CONTROL_NO."',
FORM_SUBMIT_DT = '".$FORM_SUBMIT_DT."' WHERE FORM_NO = '".$FORM_NO."'";

exit();      

*/

$stmt = $conn2->prepare("UPDATE t_form_18 SET 
MRH_CONSTITUTION_FORM = :MRH_CONSTITUTION_FORM,
TRADE_NAME = :TRADE_NAME,
PROPRIETOR_PARTNER = :PROPRIETOR_PARTNER,
PROPRIETOR_PARTNER_NAME = :PROPRIETOR_PARTNER_NAME,
PROPRIETOR_NAME_1 = :PROPRIETOR_NAME_1,
MEMBERSHIP_NUMBER_1 = :MEMBERSHIP_NUMBER_1,
CERTIFICATE_DATE_1 = :CERTIFICATE_DATE_1,
PARTNER_NAME_2 = :PARTNER_NAME_2,
MEMBERSHIP_NUMBER_2 = :MEMBERSHIP_NUMBER_2,
CERTIFICATE_DATE_2 = :CERTIFICATE_DATE_2,
PARTNER_NAME_3 = :PARTNER_NAME_3,
MEMBERSHIP_NUMBER_3 = :MEMBERSHIP_NUMBER_3,
CERTIFICATE_DATE_3 = :CERTIFICATE_DATE_3,
PARTNER_NAME_4 = :PARTNER_NAME_4,
MEMBERSHIP_NUMBER_4 = :MEMBERSHIP_NUMBER_4,
CERTIFICATE_DATE_4 = :CERTIFICATE_DATE_4,
PARTNER_NAME_5 = :PARTNER_NAME_5,
MEMBERSHIP_NUMBER_5 = :MEMBERSHIP_NUMBER_5,
CERTIFICATE_DATE_5 = :CERTIFICATE_DATE_5,
PARTNER_NAME_6 = :PARTNER_NAME_6,
MEMBERSHIP_NUMBER_6 = :MEMBERSHIP_NUMBER_6,
CERTIFICATE_DATE_6 = :CERTIFICATE_DATE_6,
FORMATION_PROPRIETORY_DATE = :FORMATION_PROPRIETORY_DATE,
PRESENT_PARTNERSHIP_DATE = :PRESENT_PARTNERSHIP_DATE,
PARTNERSHIP_STATUS = :PARTNERSHIP_STATUS,
PARTNER_SHARE_STATUS = :PARTNER_SHARE_STATUS,
DATE_PARTICULARS_APPROVAL = :DATE_PARTICULARS_APPROVAL,
FIRM_NAME = :FIRM_NAME,
ADD_HEAD_OFFICE_LINE_1 = :ADD_HEAD_OFFICE_LINE_1,
ADD_HEAD_OFFICE_LINE_2 = :ADD_HEAD_OFFICE_LINE_2,
ADD_HEAD_OFFICE_LINE_3 = :ADD_HEAD_OFFICE_LINE_3,
ADD_HEAD_OFFICE_LINE_4 = :ADD_HEAD_OFFICE_LINE_4,
HEAD_OFFICE_CITY_CODE = :HEAD_OFFICE_CITY_CODE,
HEAD_OFFICE_STATE_CODE = :HEAD_OFFICE_STATE_CODE,
HEAD_OFFICE_ZIP_POSTAL_CODE = :HEAD_OFFICE_ZIP_POSTAL_CODE,
HEAD_OFFICE_TEL = :HEAD_OFFICE_TEL,
HEAD_OFFICE_COU_CODE = :HEAD_OFFICE_COU_CODE,
HEAD_OFFICE_EMAIL = :HEAD_OFFICE_EMAIL,
HEAD_OFFICE_MOBILE = :HEAD_OFFICE_MOBILE,
SIX_MRH_RES_ADDR_LINE_1 = :SIX_MRH_RES_ADDR_LINE_1,
SIX_MRH_RES_ADDR_LINE_2 = :SIX_MRH_RES_ADDR_LINE_2,
SIX_MRH_RES_ADDR_LINE_3 = :SIX_MRH_RES_ADDR_LINE_3,
SIX_MRH_RES_ADDR_LINE_4 = :SIX_MRH_RES_ADDR_LINE_4,
SIX_MRH_RES_CITY_CODE = :SIX_MRH_RES_CITY_CODE,
SIX_MRH_RES_STATE_CODE = :SIX_MRH_RES_STATE_CODE,
SIX_MRH_RES_ZIP_POSTAL_CODE = :SIX_MRH_RES_ZIP_POSTAL_CODE,
SIX_MRH_RES_TEL = :SIX_MRH_RES_TEL,
SIX_MRH_RES_COU_CODE = :SIX_MRH_RES_COU_CODE,
SIX_MRH_RES_EMAIL = :SIX_MRH_RES_EMAIL,
SIX_MRH_RES_MOBILE = :SIX_MRH_RES_MOBILE,
SIX_TWO_MRH_RES_ADDR_LINE_1 = :SIX_TWO_MRH_RES_ADDR_LINE_1,
SIX_TWO_MRH_RES_ADDR_LINE_2 = :SIX_TWO_MRH_RES_ADDR_LINE_2,
SIX_TWO_MRH_RES_ADDR_LINE_3 = :SIX_TWO_MRH_RES_ADDR_LINE_3,
SIX_TWO_MRH_RES_ADDR_LINE_4 = :SIX_TWO_MRH_RES_ADDR_LINE_4,
SIX_TWO_MRH_RES_CITY_CODE = :SIX_TWO_MRH_RES_CITY_CODE,
SIX_TWO_MRH_RES_STATE_CODE = :SIX_TWO_MRH_RES_STATE_CODE,
SIX_TWO_MRH_RES_ZIP_POSTAL_CODE = :SIX_TWO_MRH_RES_ZIP_POSTAL_CODE,
SIX_TWO_MRH_RES_TEL = :SIX_TWO_MRH_RES_TEL,
SIX_TWO_MRH_RES_COU_CODE = :SIX_TWO_MRH_RES_COU_CODE,
SIX_TWO_MRH_RES_EMAIL = :SIX_TWO_MRH_RES_EMAIL,
SIX_TWO_MRH_RES_MOBILE = :SIX_TWO_MRH_RES_MOBILE,
SIX_THREE_MRH_RES_ADDR_LINE_1 = :SIX_THREE_MRH_RES_ADDR_LINE_1,
SIX_THREE_MRH_RES_ADDR_LINE_2 = :SIX_THREE_MRH_RES_ADDR_LINE_2,
SIX_THREE_MRH_RES_ADDR_LINE_3 = :SIX_THREE_MRH_RES_ADDR_LINE_3,
SIX_THREE_MRH_RES_ADDR_LINE_4 = :SIX_THREE_MRH_RES_ADDR_LINE_4,
SIX_THREE_MRH_RES_CITY_CODE = :SIX_THREE_MRH_RES_CITY_CODE,
SIX_THREE_MRH_RES_STATE_CODE = :SIX_THREE_MRH_RES_STATE_CODE,
SIX_THREE_MRH_RES_ZIP_POSTAL_CODE = :SIX_THREE_MRH_RES_ZIP_POSTAL_CODE,
SIX_THREE_MRH_RES_TEL = :SIX_THREE_MRH_RES_TEL,
SIX_THREE_MRH_RES_COU_CODE = :SIX_THREE_MRH_RES_COU_CODE,
SIX_THREE_MRH_RES_EMAIL = :SIX_THREE_MRH_RES_EMAIL,
SIX_THREE_MRH_RES_MOBILE = :SIX_THREE_MRH_RES_MOBILE,
PLACE_OF_BRANCH_1 = :PLACE_OF_BRANCH_1,
DATE_OF_BRANCH_1 = :DATE_OF_BRANCH_1,
PLACE_OF_BRANCH_2 = :PLACE_OF_BRANCH_2,
DATE_OF_BRANCH_2 = :DATE_OF_BRANCH_2,
PLACE_OF_BRANCH_3 = :PLACE_OF_BRANCH_3,
DATE_OF_BRANCH_3 = :DATE_OF_BRANCH_3,
PLACE_OF_BRANCH_4 = :PLACE_OF_BRANCH_4,
DATE_OF_BRANCH_4 = :DATE_OF_BRANCH_4,
PLACE_OF_BRANCH_5 = :PLACE_OF_BRANCH_5,
DATE_OF_BRANCH_5 = :DATE_OF_BRANCH_5,
BRANCH_OFFICE = :BRANCH_OFFICE,
MEMBER_IN_CHARGE = :MEMBER_IN_CHARGE,
MEMBER_NUMBER = :MEMBER_NUMBER,
BRANCH_OFFICE_1 = :BRANCH_OFFICE_1,
MEMBER_IN_CHARGE_1 = :MEMBER_IN_CHARGE_1,
MEMBER_NUMBER_1 = :MEMBER_NUMBER_1,
BRANCH_OFFICE_2 = :BRANCH_OFFICE_2,
MEMBER_IN_CHARGE_2 = :MEMBER_IN_CHARGE_2,
MEMBER_NUMBER_2 = :MEMBER_NUMBER_2,
BRANCH_OFFICE_3 = :BRANCH_OFFICE_3,
MEMBER_IN_CHARGE_3 = :MEMBER_IN_CHARGE_3,
MEMBER_NUMBER_3 = :MEMBER_NUMBER_3,
BRANCH_OFFICE_4 = :BRANCH_OFFICE_4,
MEMBER_IN_CHARGE_4 = :MEMBER_IN_CHARGE_4,
MEMBER_NUMBER_4 = :MEMBER_NUMBER_4,
MRH_PRO_PARTNER = :MRH_PRO_PARTNER,
PAR_PRO_PA_NAME = :PAR_PRO_PA_NAME,
CA_FIRM_NAME = :CA_FIRM_NAME,
CAPACITY_CONNECTED = :CAPACITY_CONNECTED,
OCCUPATION_DETAILS = :OCCUPATION_DETAILS,
PAR_PRO_PA_NAME_1 = :PAR_PRO_PA_NAME_1,
CA_FIRM_NAME_1 = :CA_FIRM_NAME_1,
CAPACITY_CONNECTED_1 = :CAPACITY_CONNECTED_1,
OCCUPATION_DETAILS_1 = :OCCUPATION_DETAILS_1,
PAR_PRO_PA_NAME_2 = :PAR_PRO_PA_NAME_2,
CA_FIRM_NAME_2 = :CA_FIRM_NAME_2,
CAPACITY_CONNECTED_2 = :CAPACITY_CONNECTED_2,
OCCUPATION_DETAILS_2 = :OCCUPATION_DETAILS_2,
PAR_PRO_PA_NAME_3 = :PAR_PRO_PA_NAME_3,
CA_FIRM_NAME_3 = :CA_FIRM_NAME_3,
CAPACITY_CONNECTED_3 = :CAPACITY_CONNECTED_3,
OCCUPATION_DETAILS_3 = :OCCUPATION_DETAILS_3,
FIRM_IND_PAR_NAME = :FIRM_IND_PAR_NAME,
FIRM_MEM_NAME_LINE_1 = :FIRM_MEM_NAME_LINE_1,
FIRM_MEMBERSHIP_NUMBER_LINE_1 = :FIRM_MEMBERSHIP_NUMBER_LINE_1,
FIRM_MEM_NAME_LINE_2 = :FIRM_MEM_NAME_LINE_2,
FIRM_MEMBERSHIP_NUMBER_LINE_2 = :FIRM_MEMBERSHIP_NUMBER_LINE_2,
FIRM_MEM_NAME_LINE_3 = :FIRM_MEM_NAME_LINE_3,
FIRM_MEMBERSHIP_NUMBER_LINE_3 = :FIRM_MEMBERSHIP_NUMBER_LINE_3,
FIRM_MEM_NAME_LINE_4 = :FIRM_MEM_NAME_LINE_4,
FIRM_MEMBERSHIP_NUMBER_LINE_4 = :FIRM_MEMBERSHIP_NUMBER_LINE_4,
FIRM_MEM_NAME_LINE_5 = :FIRM_MEM_NAME_LINE_5,
FIRM_MEMBERSHIP_NUMBER_LINE_5 = :FIRM_MEMBERSHIP_NUMBER_LINE_5,
INS_MEM_NAME_LINE_1 = :INS_MEM_NAME_LINE_1,
INS_MEM_NUMBER_LINE_1 = :INS_MEM_NUMBER_LINE_1,
INS_MEM_DOJ_LINE_1 = :INS_MEM_DOJ_LINE_1,
INS_MEM_NAME_LINE_2 = :INS_MEM_NAME_LINE_2,
INS_MEM_NUMBER_LINE_2 = :INS_MEM_NUMBER_LINE_2,
INS_MEM_DOJ_LINE_2 = :INS_MEM_DOJ_LINE_2,
INS_MEM_NAME_LINE_3 = :INS_MEM_NAME_LINE_3,
INS_MEM_NUMBER_LINE_3 = :INS_MEM_NUMBER_LINE_3,
INS_MEM_DOJ_LINE_3 = :INS_MEM_DOJ_LINE_3,
INS_MEM_NAME_LINE_4 = :INS_MEM_NAME_LINE_4,
INS_MEM_NUMBER_LINE_4 = :INS_MEM_NUMBER_LINE_4,
INS_MEM_DOJ_LINE_4 = :INS_MEM_DOJ_LINE_4,
INS_MEM_NAME_LINE_5 = :INS_MEM_NAME_LINE_5,
INS_MEM_NUMBER_LINE_5 = :INS_MEM_NUMBER_LINE_5,
INS_MEM_DOJ_LINE_5 = :INS_MEM_DOJ_LINE_5,
PAID_ASSISTANT = :PAID_ASSISTANT,
PAID_ASSISTANCE_NAME_LINE_1 = :PAID_ASSISTANCE_NAME_LINE_1,
ENGAGED_PAR_PRO_PA_NAME_LINE_1 = :ENGAGED_PAR_PRO_PA_NAME_LINE_1,
ENGAGED_CAP_CONN_LINE_1 = :ENGAGED_CAP_CONN_LINE_1,
PAID_ASSISTANCE_NAME_LINE_2 = :PAID_ASSISTANCE_NAME_LINE_2,
ENGAGED_PAR_PRO_PA_NAME_LINE_2 = :ENGAGED_PAR_PRO_PA_NAME_LINE_2,
ENGAGED_CAP_CONN_LINE_2 = :ENGAGED_CAP_CONN_LINE_2,
PAID_ASSISTANCE_NAME_LINE_3 = :PAID_ASSISTANCE_NAME_LINE_3,
ENGAGED_PAR_PRO_PA_NAME_LINE_3 = :ENGAGED_PAR_PRO_PA_NAME_LINE_3,
ENGAGED_CAP_CONN_LINE_3 = :ENGAGED_CAP_CONN_LINE_3,
PAID_ASSISTANCE_STATUS = :PAID_ASSISTANCE_STATUS,
INDIVISUAL_PA_NAME_LINE_1 = :INDIVISUAL_PA_NAME_LINE_1,
INDIVISUAL_PA_MEM_NO_LINE_1 = :INDIVISUAL_PA_MEM_NO_LINE_1,
INDIVISUAL_PA_NAME_LINE_2 = :INDIVISUAL_PA_NAME_LINE_2,
INDIVISUAL_PA_MEM_NO_LINE_2 = :INDIVISUAL_PA_MEM_NO_LINE_2,
INDIVISUAL_PA_NAME_LINE_3 = :INDIVISUAL_PA_NAME_LINE_3,
INDIVISUAL_PA_MEM_NO_LINE_3 = :INDIVISUAL_PA_MEM_NO_LINE_3,
INDIVISUAL_PA_NAME_LINE_4 = :INDIVISUAL_PA_NAME_LINE_4,
INDIVISUAL_PA_MEM_NO_LINE_4 = :INDIVISUAL_PA_MEM_NO_LINE_4,
INDIVISUAL_PA_MEM_DATE = :INDIVISUAL_PA_MEM_DATE,
INDIVISUAL_PA_MEM_PLACE = :INDIVISUAL_PA_MEM_PLACE,
SIGNATURE_MM_NUMBER_1 = :SIGNATURE_MM_NUMBER_1,
SIGNATURE_MM_NUMBER_2 = :SIGNATURE_MM_NUMBER_2,
SIGNATURE_MM_NUMBER_3 = :SIGNATURE_MM_NUMBER_3,
SIGNATURE_MM_NUMBER_4 = :SIGNATURE_MM_NUMBER_4,
SIGNATURE_MM_NUMBER_5 = :SIGNATURE_MM_NUMBER_5,
SIGNATURE_MM_NUMBER_6 = :SIGNATURE_MM_NUMBER_6,





MRH_MRN = :MRH_MRN,
FORM_SAVE_STATUS = :FORM_SAVE_STATUS,
DELAY_FEE = :DELAY_FEE,
TOTAL_AMT = :TOTAL_AMT WHERE FORM_NO = :FORM_NO
");

//$stmt->bindValue(':STUD_PART1_MEMBER_NO', $STUD_PART1_MEMBER_NO);
$stmt->bindValue(':MRH_CONSTITUTION_FORM', $MRH_CONSTITUTION_FORM);
$stmt->bindValue(':TRADE_NAME', $TRADE_NAME);
$stmt->bindValue(':PROPRIETOR_PARTNER', $PROPRIETOR_PARTNER);
$stmt->bindValue(':PROPRIETOR_PARTNER_NAME', $PROPRIETOR_PARTNER_NAME);
$stmt->bindValue(':PROPRIETOR_NAME_1', $PROPRIETOR_NAME_1);
$stmt->bindValue(':MEMBERSHIP_NUMBER_1', $MEMBERSHIP_NUMBER_1);
$stmt->bindValue(':CERTIFICATE_DATE_1', $CERTIFICATE_DATE_1);
$stmt->bindValue(':PARTNER_NAME_2', $PARTNER_NAME_2);
$stmt->bindValue(':MEMBERSHIP_NUMBER_2', $MEMBERSHIP_NUMBER_2);
$stmt->bindValue(':CERTIFICATE_DATE_2', $CERTIFICATE_DATE_2);
$stmt->bindValue(':PARTNER_NAME_3', $PARTNER_NAME_3);
$stmt->bindValue(':MEMBERSHIP_NUMBER_3', $MEMBERSHIP_NUMBER_3);
$stmt->bindValue(':CERTIFICATE_DATE_3', $CERTIFICATE_DATE_3);
$stmt->bindValue(':PARTNER_NAME_4', $PARTNER_NAME_4);
$stmt->bindValue(':MEMBERSHIP_NUMBER_4', $MEMBERSHIP_NUMBER_4);
$stmt->bindValue(':CERTIFICATE_DATE_4', $CERTIFICATE_DATE_4);
$stmt->bindValue(':PARTNER_NAME_5', $PARTNER_NAME_5);
$stmt->bindValue(':MEMBERSHIP_NUMBER_5', $MEMBERSHIP_NUMBER_5);
$stmt->bindValue(':CERTIFICATE_DATE_5', $CERTIFICATE_DATE_5);
$stmt->bindValue(':PARTNER_NAME_6', $PARTNER_NAME_6);
$stmt->bindValue(':MEMBERSHIP_NUMBER_6', $MEMBERSHIP_NUMBER_6);
$stmt->bindValue(':CERTIFICATE_DATE_6', $CERTIFICATE_DATE_6);
$stmt->bindValue(':FORMATION_PROPRIETORY_DATE', $FORMATION_PROPRIETORY_DATE);
$stmt->bindValue(':PRESENT_PARTNERSHIP_DATE', $PRESENT_PARTNERSHIP_DATE);
$stmt->bindValue(':PARTNERSHIP_STATUS', $PARTNERSHIP_STATUS);
$stmt->bindValue(':PARTNER_SHARE_STATUS', $PARTNER_SHARE_STATUS);
$stmt->bindValue(':DATE_PARTICULARS_APPROVAL', $DATE_PARTICULARS_APPROVAL);
$stmt->bindValue(':FIRM_NAME', $FIRM_NAME);
$stmt->bindValue(':ADD_HEAD_OFFICE_LINE_1', $ADD_HEAD_OFFICE_LINE_1);
$stmt->bindValue(':ADD_HEAD_OFFICE_LINE_2', $ADD_HEAD_OFFICE_LINE_2);
$stmt->bindValue(':ADD_HEAD_OFFICE_LINE_3', $ADD_HEAD_OFFICE_LINE_3);
$stmt->bindValue(':ADD_HEAD_OFFICE_LINE_4', $ADD_HEAD_OFFICE_LINE_4);
$stmt->bindValue(':HEAD_OFFICE_CITY_CODE', $HEAD_OFFICE_CITY_CODE);
$stmt->bindValue(':HEAD_OFFICE_STATE_CODE', $HEAD_OFFICE_STATE_CODE);
$stmt->bindValue(':HEAD_OFFICE_ZIP_POSTAL_CODE', $HEAD_OFFICE_ZIP_POSTAL_CODE);
$stmt->bindValue(':HEAD_OFFICE_TEL', $HEAD_OFFICE_TEL);
$stmt->bindValue(':HEAD_OFFICE_COU_CODE', $HEAD_OFFICE_COU_CODE);
$stmt->bindValue(':HEAD_OFFICE_EMAIL', $HEAD_OFFICE_EMAIL);
$stmt->bindValue(':HEAD_OFFICE_MOBILE', $HEAD_OFFICE_MOBILE);
$stmt->bindValue(':SIX_MRH_RES_ADDR_LINE_1', $SIX_MRH_RES_ADDR_LINE_1);
$stmt->bindValue(':SIX_MRH_RES_ADDR_LINE_2', $SIX_MRH_RES_ADDR_LINE_2);
$stmt->bindValue(':SIX_MRH_RES_ADDR_LINE_3', $SIX_MRH_RES_ADDR_LINE_3);
$stmt->bindValue(':SIX_MRH_RES_ADDR_LINE_4', $SIX_MRH_RES_ADDR_LINE_4);
$stmt->bindValue(':SIX_MRH_RES_CITY_CODE', $SIX_MRH_RES_CITY_CODE);
$stmt->bindValue(':SIX_MRH_RES_STATE_CODE', $SIX_MRH_RES_STATE_CODE);
$stmt->bindValue(':SIX_MRH_RES_ZIP_POSTAL_CODE', $SIX_MRH_RES_ZIP_POSTAL_CODE);
$stmt->bindValue(':SIX_MRH_RES_TEL', $SIX_MRH_RES_TEL);
$stmt->bindValue(':SIX_MRH_RES_COU_CODE', $SIX_MRH_RES_COU_CODE);
$stmt->bindValue(':SIX_MRH_RES_EMAIL', $SIX_MRH_RES_EMAIL);
$stmt->bindValue(':SIX_MRH_RES_MOBILE', $SIX_MRH_RES_MOBILE);
$stmt->bindValue(':SIX_TWO_MRH_RES_ADDR_LINE_1', $SIX_TWO_MRH_RES_ADDR_LINE_1);
$stmt->bindValue(':SIX_TWO_MRH_RES_ADDR_LINE_2', $SIX_TWO_MRH_RES_ADDR_LINE_2);
$stmt->bindValue(':SIX_TWO_MRH_RES_ADDR_LINE_3', $SIX_TWO_MRH_RES_ADDR_LINE_3);
$stmt->bindValue(':SIX_TWO_MRH_RES_ADDR_LINE_4', $SIX_TWO_MRH_RES_ADDR_LINE_4);
$stmt->bindValue(':SIX_TWO_MRH_RES_CITY_CODE', $SIX_TWO_MRH_RES_CITY_CODE);
$stmt->bindValue(':SIX_TWO_MRH_RES_STATE_CODE', $SIX_TWO_MRH_RES_STATE_CODE);
$stmt->bindValue(':SIX_TWO_MRH_RES_ZIP_POSTAL_CODE', $SIX_TWO_MRH_RES_ZIP_POSTAL_CODE);
$stmt->bindValue(':SIX_TWO_MRH_RES_TEL', $SIX_TWO_MRH_RES_TEL);
$stmt->bindValue(':SIX_TWO_MRH_RES_COU_CODE', $SIX_TWO_MRH_RES_COU_CODE);
$stmt->bindValue(':SIX_TWO_MRH_RES_EMAIL', $SIX_TWO_MRH_RES_EMAIL);
$stmt->bindValue(':SIX_TWO_MRH_RES_MOBILE', $SIX_TWO_MRH_RES_MOBILE);
$stmt->bindValue(':SIX_THREE_MRH_RES_ADDR_LINE_1', $SIX_THREE_MRH_RES_ADDR_LINE_1);
$stmt->bindValue(':SIX_THREE_MRH_RES_ADDR_LINE_2', $SIX_THREE_MRH_RES_ADDR_LINE_2);
$stmt->bindValue(':SIX_THREE_MRH_RES_ADDR_LINE_3', $SIX_THREE_MRH_RES_ADDR_LINE_3);
$stmt->bindValue(':SIX_THREE_MRH_RES_ADDR_LINE_4', $SIX_THREE_MRH_RES_ADDR_LINE_4);
$stmt->bindValue(':SIX_THREE_MRH_RES_CITY_CODE', $SIX_THREE_MRH_RES_CITY_CODE);
$stmt->bindValue(':SIX_THREE_MRH_RES_STATE_CODE', $SIX_THREE_MRH_RES_STATE_CODE);
$stmt->bindValue(':SIX_THREE_MRH_RES_ZIP_POSTAL_CODE', $SIX_THREE_MRH_RES_ZIP_POSTAL_CODE);
$stmt->bindValue(':SIX_THREE_MRH_RES_TEL', $SIX_THREE_MRH_RES_TEL);
$stmt->bindValue(':SIX_THREE_MRH_RES_COU_CODE', $SIX_THREE_MRH_RES_COU_CODE);
$stmt->bindValue(':SIX_THREE_MRH_RES_EMAIL', $SIX_THREE_MRH_RES_EMAIL);
$stmt->bindValue(':SIX_THREE_MRH_RES_MOBILE', $SIX_THREE_MRH_RES_MOBILE);
$stmt->bindValue(':PLACE_OF_BRANCH_1', $PLACE_OF_BRANCH_1);
$stmt->bindValue(':DATE_OF_BRANCH_1', $DATE_OF_BRANCH_1);
$stmt->bindValue(':PLACE_OF_BRANCH_2', $PLACE_OF_BRANCH_2);
$stmt->bindValue(':DATE_OF_BRANCH_2', $DATE_OF_BRANCH_2);
$stmt->bindValue(':PLACE_OF_BRANCH_3', $PLACE_OF_BRANCH_3);
$stmt->bindValue(':DATE_OF_BRANCH_3', $DATE_OF_BRANCH_3);
$stmt->bindValue(':PLACE_OF_BRANCH_4', $PLACE_OF_BRANCH_4);
$stmt->bindValue(':DATE_OF_BRANCH_4', $DATE_OF_BRANCH_4);
$stmt->bindValue(':PLACE_OF_BRANCH_5', $PLACE_OF_BRANCH_5);
$stmt->bindValue(':DATE_OF_BRANCH_5', $DATE_OF_BRANCH_5);
$stmt->bindValue(':BRANCH_OFFICE', $BRANCH_OFFICE);
$stmt->bindValue(':MEMBER_IN_CHARGE', $MEMBER_IN_CHARGE);
$stmt->bindValue(':MEMBER_NUMBER', $MEMBER_NUMBER);
$stmt->bindValue(':BRANCH_OFFICE_1', $BRANCH_OFFICE_1);
$stmt->bindValue(':MEMBER_IN_CHARGE_1', $MEMBER_IN_CHARGE_1);
$stmt->bindValue(':MEMBER_NUMBER_1', $MEMBER_NUMBER_1);
$stmt->bindValue(':BRANCH_OFFICE_2', $BRANCH_OFFICE_2);
$stmt->bindValue(':MEMBER_IN_CHARGE_2', $MEMBER_IN_CHARGE_2);
$stmt->bindValue(':MEMBER_NUMBER_2', $MEMBER_NUMBER_2);
$stmt->bindValue(':BRANCH_OFFICE_3', $BRANCH_OFFICE_3);
$stmt->bindValue(':MEMBER_IN_CHARGE_3', $MEMBER_IN_CHARGE_3);
$stmt->bindValue(':MEMBER_NUMBER_3', $MEMBER_NUMBER_3);
$stmt->bindValue(':BRANCH_OFFICE_4', $BRANCH_OFFICE_4);
$stmt->bindValue(':MEMBER_IN_CHARGE_4', $MEMBER_IN_CHARGE_4);
$stmt->bindValue(':MEMBER_NUMBER_4', $MEMBER_NUMBER_4);
$stmt->bindValue(':MRH_PRO_PARTNER', $MRH_PRO_PARTNER);
$stmt->bindValue(':PAR_PRO_PA_NAME', $PAR_PRO_PA_NAME);
$stmt->bindValue(':CA_FIRM_NAME', $CA_FIRM_NAME);
$stmt->bindValue(':CAPACITY_CONNECTED', $CAPACITY_CONNECTED);
$stmt->bindValue(':OCCUPATION_DETAILS', $OCCUPATION_DETAILS);
$stmt->bindValue(':PAR_PRO_PA_NAME_1', $PAR_PRO_PA_NAME_1);
$stmt->bindValue(':CA_FIRM_NAME_1', $CA_FIRM_NAME_1);
$stmt->bindValue(':CAPACITY_CONNECTED_1', $CAPACITY_CONNECTED_1);
$stmt->bindValue(':OCCUPATION_DETAILS_1', $OCCUPATION_DETAILS_1);
$stmt->bindValue(':PAR_PRO_PA_NAME_2', $PAR_PRO_PA_NAME_2);
$stmt->bindValue(':CA_FIRM_NAME_2', $CA_FIRM_NAME_2);
$stmt->bindValue(':CAPACITY_CONNECTED_2', $CAPACITY_CONNECTED_2);
$stmt->bindValue(':OCCUPATION_DETAILS_2', $OCCUPATION_DETAILS_2);
$stmt->bindValue(':PAR_PRO_PA_NAME_3', $PAR_PRO_PA_NAME_3);
$stmt->bindValue(':CA_FIRM_NAME_3', $CA_FIRM_NAME_3);
$stmt->bindValue(':CAPACITY_CONNECTED_3', $CAPACITY_CONNECTED_3);
$stmt->bindValue(':OCCUPATION_DETAILS_3', $OCCUPATION_DETAILS_3);
$stmt->bindValue(':FIRM_IND_PAR_NAME', $FIRM_IND_PAR_NAME);
$stmt->bindValue(':FIRM_MEM_NAME_LINE_1', $FIRM_MEM_NAME_LINE_1);
$stmt->bindValue(':FIRM_MEMBERSHIP_NUMBER_LINE_1', $FIRM_MEMBERSHIP_NUMBER_LINE_1);
$stmt->bindValue(':FIRM_MEM_NAME_LINE_2', $FIRM_MEM_NAME_LINE_2);
$stmt->bindValue(':FIRM_MEMBERSHIP_NUMBER_LINE_2', $FIRM_MEMBERSHIP_NUMBER_LINE_2);
$stmt->bindValue(':FIRM_MEM_NAME_LINE_3', $FIRM_MEM_NAME_LINE_3);
$stmt->bindValue(':FIRM_MEMBERSHIP_NUMBER_LINE_3', $FIRM_MEMBERSHIP_NUMBER_LINE_3);
$stmt->bindValue(':FIRM_MEM_NAME_LINE_4', $FIRM_MEM_NAME_LINE_4);
$stmt->bindValue(':FIRM_MEMBERSHIP_NUMBER_LINE_4', $FIRM_MEMBERSHIP_NUMBER_LINE_4);
$stmt->bindValue(':FIRM_MEM_NAME_LINE_5', $FIRM_MEM_NAME_LINE_5);
$stmt->bindValue(':FIRM_MEMBERSHIP_NUMBER_LINE_5', $FIRM_MEMBERSHIP_NUMBER_LINE_5);
$stmt->bindValue(':INS_MEM_NAME_LINE_1', $INS_MEM_NAME_LINE_1);
$stmt->bindValue(':INS_MEM_NUMBER_LINE_1', $INS_MEM_NUMBER_LINE_1);
$stmt->bindValue(':INS_MEM_DOJ_LINE_1', $INS_MEM_DOJ_LINE_1);
$stmt->bindValue(':INS_MEM_NAME_LINE_2', $INS_MEM_NAME_LINE_2);
$stmt->bindValue(':INS_MEM_NUMBER_LINE_2', $INS_MEM_NUMBER_LINE_2);
$stmt->bindValue(':INS_MEM_DOJ_LINE_2', $INS_MEM_DOJ_LINE_2);
$stmt->bindValue(':INS_MEM_NAME_LINE_3', $INS_MEM_NAME_LINE_3);
$stmt->bindValue(':INS_MEM_NUMBER_LINE_3', $INS_MEM_NUMBER_LINE_3);
$stmt->bindValue(':INS_MEM_DOJ_LINE_3', $INS_MEM_DOJ_LINE_3);
$stmt->bindValue(':INS_MEM_NAME_LINE_4', $INS_MEM_NAME_LINE_4);
$stmt->bindValue(':INS_MEM_NUMBER_LINE_4', $INS_MEM_NUMBER_LINE_4);
$stmt->bindValue(':INS_MEM_DOJ_LINE_4', $INS_MEM_DOJ_LINE_4);
$stmt->bindValue(':INS_MEM_NAME_LINE_5', $INS_MEM_NAME_LINE_5);
$stmt->bindValue(':INS_MEM_NUMBER_LINE_5', $INS_MEM_NUMBER_LINE_5);
$stmt->bindValue(':INS_MEM_DOJ_LINE_5', $INS_MEM_DOJ_LINE_5);
$stmt->bindValue(':PAID_ASSISTANT', $PAID_ASSISTANT);
$stmt->bindValue(':PAID_ASSISTANCE_NAME_LINE_1', $PAID_ASSISTANCE_NAME_LINE_1);
$stmt->bindValue(':ENGAGED_PAR_PRO_PA_NAME_LINE_1', $ENGAGED_PAR_PRO_PA_NAME_LINE_1);
$stmt->bindValue(':ENGAGED_CAP_CONN_LINE_1', $ENGAGED_CAP_CONN_LINE_1);
$stmt->bindValue(':PAID_ASSISTANCE_NAME_LINE_2', $PAID_ASSISTANCE_NAME_LINE_2);
$stmt->bindValue(':ENGAGED_PAR_PRO_PA_NAME_LINE_2', $ENGAGED_PAR_PRO_PA_NAME_LINE_2);
$stmt->bindValue(':ENGAGED_CAP_CONN_LINE_2', $ENGAGED_CAP_CONN_LINE_2);
$stmt->bindValue(':PAID_ASSISTANCE_NAME_LINE_3', $PAID_ASSISTANCE_NAME_LINE_3);
$stmt->bindValue(':ENGAGED_PAR_PRO_PA_NAME_LINE_3', $ENGAGED_PAR_PRO_PA_NAME_LINE_3);
$stmt->bindValue(':ENGAGED_CAP_CONN_LINE_3', $ENGAGED_CAP_CONN_LINE_3);
$stmt->bindValue(':PAID_ASSISTANCE_STATUS', $PAID_ASSISTANCE_STATUS);
$stmt->bindValue(':INDIVISUAL_PA_NAME_LINE_1', $INDIVISUAL_PA_NAME_LINE_1);
$stmt->bindValue(':INDIVISUAL_PA_MEM_NO_LINE_1', $INDIVISUAL_PA_MEM_NO_LINE_1);
$stmt->bindValue(':INDIVISUAL_PA_NAME_LINE_2', $INDIVISUAL_PA_NAME_LINE_2);
$stmt->bindValue(':INDIVISUAL_PA_MEM_NO_LINE_2', $INDIVISUAL_PA_MEM_NO_LINE_2);
$stmt->bindValue(':INDIVISUAL_PA_NAME_LINE_3', $INDIVISUAL_PA_NAME_LINE_3);
$stmt->bindValue(':INDIVISUAL_PA_MEM_NO_LINE_3', $INDIVISUAL_PA_MEM_NO_LINE_3);
$stmt->bindValue(':INDIVISUAL_PA_NAME_LINE_4', $INDIVISUAL_PA_NAME_LINE_4);
$stmt->bindValue(':INDIVISUAL_PA_MEM_NO_LINE_4', $INDIVISUAL_PA_MEM_NO_LINE_4);
$stmt->bindValue(':INDIVISUAL_PA_MEM_DATE', $INDIVISUAL_PA_MEM_DATE);
$stmt->bindValue(':INDIVISUAL_PA_MEM_PLACE', $INDIVISUAL_PA_MEM_PLACE);
$stmt->bindValue(':SIGNATURE_MM_NUMBER_1', $SIGNATURE_MM_NUMBER_1);
$stmt->bindValue(':SIGNATURE_MM_NUMBER_2', $SIGNATURE_MM_NUMBER_2);
$stmt->bindValue(':SIGNATURE_MM_NUMBER_3', $SIGNATURE_MM_NUMBER_3);
$stmt->bindValue(':SIGNATURE_MM_NUMBER_4', $SIGNATURE_MM_NUMBER_4);
$stmt->bindValue(':SIGNATURE_MM_NUMBER_5', $SIGNATURE_MM_NUMBER_5);
$stmt->bindValue(':SIGNATURE_MM_NUMBER_6', $SIGNATURE_MM_NUMBER_6);


//$stmt->bindValue(':STUD_PART1_VIDE_REGISTRATION', $STUD_PART1_VIDE_REGISTRATION);

$stmt->bindValue(':MRH_MRN', $MRH_MRN);
$stmt->bindValue(':FORM_SAVE_STATUS', $FORM_SAVE_STATUS);
$stmt->bindValue(':DELAY_FEE', $DELAY_FEE);
$stmt->bindValue(':TOTAL_AMT', $TOTAL_AMT);
$stmt->bindValue(':FORM_NO', $FORM_NO);
/*

$stmt->bindValue(':MRH_MRN', $MRH_MRN);
$stmt->bindValue(':FORM_NO', $FORM_NO);
$stmt->bindValue(':FORM_SAVE_STATUS', $FORM_SAVE_STATUS); */
//$stmt->bindValue(':STUD_REGION_CODE', $STUD_REGION_CODE);


$res = $stmt->execute();
if($res === false){
	$error = $stmt->errorInfo();
	//print_r($error);die;
	file_put_contents('error_log.txt', 'Date : '.date('d-m-Y h:i:s').' ::'.$error[2].' for '.$MRH_MRN.PHP_EOL, FILE_APPEND);
}else{
	if($FORM_SAVE_STATUS == 1 && $TOTAL_AMT == 0){
		trans_data_to_delhi_new_form18($MRH_MRN, $FORM_NO);
		header('location:dashboard.php');
	}
}
	
}
/*********************** UPDATE USER DATA IN TRANSACTION TABLE END ***************/


/*********************** GET USER DATA FORM 109 TRANSACTION TABLE START ***************/
function get_user_data_form18(){
	global $conn2;
	
	$MRH_MRN=$_SESSION['UserID'];	
	$result5 = $conn2->query("SET NAMES utf8");	 
	$stmt = $conn2->prepare("SELECT * FROM t_form_18 WHERE MRH_MRN =? AND NAME_RESTORING_CONTROL_NO IS NULL");
	$stmt->bindValue(1,$MRH_MRN);	
	$stmt->execute();
	$result5=$stmt->fetchAll(PDO::FETCH_ASSOC);
	// echo "yhjh";
	//echo "<pre>";print_r($result5[0]);die;
	if (count($result5) > 0) {		     
		return $result5[0];		  
	}else{
		return 1;
	}	
}
/*********************** GET USER DATA FORM 109 TRANSACTION TABLE END ***************/




/******************* FORM STATUS 1 FOR DASHBOARD START ***************/ 
 function get_form18_status(){
	global $conn2;
	global $wwwroot;
	$MRH_MRN = $_SESSION['MRH_MRN'];
	$result4 = $conn2->query("SET NAMES utf8");	  
	$stmt = $conn2->prepare("SELECT FORM_NO,MRH_MRN,MRH_PDF_PATH,NAME_RESTORING_CONTROL_NO FROM t_form_18 WHERE MRH_MRN =? AND NAME_RESTORING_CONTROL_NO <> ''");
	$stmt->bindValue(1,$MRH_MRN);		 
	$stmt->execute();
	$result2=$stmt->fetchAll(PDO::FETCH_ASSOC);
	if(count($result2) > 0){
		$form18_status = '';
		$count = 0;
		foreach($result2 as $row){
			$count = $count + 1;
			$form18_status .= '<tr><td>'.$count.'</td><td>Form 18 </td>';
			if($row['NAME_RESTORING_CONTROL_NO'] != ''){
				$form18_status .="<td>";
				if($row['MRH_PDF_PATH'] == ''){
					$form18_status .="<a href='".$wwwroot."/FormPDF/pdf/form18.php?ROW_ID=".$row['FORM_NO']."' target='_blank'>Generate PDF</a>";
				}else{
					$form18_status .="<a href='".$wwwroot."/generated_pdf/form18/".$row['MRH_PDF_PATH']."' target='_blank'>View PDF</a>";
				}
				$form18_status .="</td>";
			}else{
				$form18_status .='<td></td>';
			}
			$form18_status .= '</tr>';
		}	
	}else{
		$form18_status = '<tr><td colspan="3"><strong>No Form Submit !</strong></td></tr>';
	}
	echo $form18_status;
} 
/******************* FORM STATUS 1 FOR DASHBOARD END ***************/


/*********************** ADD PDF PATH START ***************/
/* function add_pdf_path_student_109($STUD_PDF_PATH,$MRH_MRN,$FORM_NO){	    
    global $conn2;
	
    $stmt = $conn2->prepare("UPDATE t_form_109 SET STUD_PDF_PATH= :STUD_PDF_PATH WHERE FORM_NO = :FORM_NO AND MRH_MRN = :MRH_MRN");
	$stmt->bindValue(':STUD_PDF_PATH',$STUD_PDF_PATH);
	$stmt->bindValue(':FORM_NO',$FORM_NO);
	$stmt->bindValue(':MRH_MRN',$MRH_MRN);
    $stmt->execute();
	return 1;
} */
/*********************** ADD PDF PATH END ***************/

/*********************** GET USER DATA FORM 103 TRANSACTION TABLE START ***************/ // 15 NOV 2016 updated
 function get_user_data_form18_rowid($FORM_NO){
	global $conn2;
	$MRH_MRN=$_SESSION['UserID'];
	
	$result5 = $conn2->query("SET NAMES utf8");	 
	
	$stmt = $conn2->prepare("SELECT * FROM t_form_18 t WHERE t.MRH_MRN =? AND t.FORM_NO=?");	
	//$stmt = $conn2->prepare("SELECT * FROM t_form_18 t WHERE t.MRH_MRN ='000796'  AND t.FORM_NO= '89'");
 //  $stmt = $conn2->prepare("SELECT * FROM t_form_18 t WHERE FORM_NO= $FORM_NO");	
         
	$stmt->bindValue(1,$MRH_MRN);
	$stmt->bindValue(2,$FORM_NO);
	$stmt->execute();
	$result5=$stmt->fetchAll(PDO::FETCH_ASSOC);
	if (count($result5) > 0) {		     
		return $result5[0];		  
	}else{
		return 1;
	}	
} 
/*********************** GET USER DATA FORM 103 TRANSACTION TABLE END ***************/


/* function get_stud_region($MRH_MRN){
	global $conn2;
	$result5 = $conn2->query("SET NAMES utf8");	 	
	$stmt = $conn2->prepare("SELECT STUD_REGION_CODE FROM student_mst t WHERE t.MRH_MRN =?");		  
	$stmt->bindValue(1,$MRH_MRN);
	$stmt->execute();
	$result5=$stmt->fetchAll(PDO::FETCH_ASSOC);
	if (count($result5) > 0) {		     
		$res = $result5[0]['STUD_REGION_CODE'];		  
	}else{
		$res = '';
	}	
	
	return $res;
} */

/* function transfer_data_to_delhi_form109($MRH_MRN, $FORM_NO){
	include('../includes/dbconnect_delhi.php');
	global $conn2;
	global $conn4;

	if($conn4){      
	    //$result4 = $conn2->query("SET NAMES utf8");	  
		$stmt = $conn2->prepare("SELECT * FROM t_form_109 WHERE MRH_MRN =? AND FORM_NO =?");
		$stmt->bindValue(1,$MRH_MRN);		 
		$stmt->bindValue(2,$FORM_NO);		 
		$stmt->execute();
		$result2=$stmt->fetchAll(PDO::FETCH_ASSOC);
		if(count($result2) > 0){			 
		    $row=$result2[0];			
			$TERMINATE_CONTROL_NO =  $row['TERMINATE_CONTROL_NO'];								
			$stmt3 = $conn4->prepare("SELECT MRH_MRN FROM t_form_109 WHERE MRH_MRN= ? AND TERMINATE_CONTROL_NO = ?" );
			$stmt3->bindValue(1,$MRH_MRN);
			$stmt3->bindValue(2,$TERMINATE_CONTROL_NO);
			$stmt3->execute();
			$result3=$stmt3->fetchAll();
			if(count($result3) > 0){ 
				echo "Data Already Imported";
			}else{ 
			
			$STUD_PART1_FROM_DT = $row['STUD_PART1_FROM_DT'];
			$STUD_PART1_FROM_DT = !empty($STUD_PART1_FROM_DT) ? $STUD_PART1_FROM_DT : NULL;
			
			$STUD_PART1_TO_DT = $row['STUD_PART1_TO_DT'];
			$STUD_PART1_TO_DT = !empty($STUD_PART1_TO_DT) ? $STUD_PART1_TO_DT : NULL;
			
			$STUD_PART1_TERMINATED_DT = $row['STUD_PART1_TERMINATED_DT'];
			$STUD_PART1_TERMINATED_DT = !empty($STUD_PART1_TERMINATED_DT) ? $STUD_PART1_TERMINATED_DT : NULL;
			
			$STUD_PART3_COMMENCEMENT_DT = $row['STUD_PART3_COMMENCEMENT_DT'];
			$STUD_PART3_COMMENCEMENT_DT = !empty($STUD_PART3_COMMENCEMENT_DT) ? $STUD_PART3_COMMENCEMENT_DT : NULL;
			
			$STUD_PART3_FROM_DT = $row['STUD_PART3_FROM_DT'];
			$STUD_PART3_FROM_DT = !empty($STUD_PART3_FROM_DT) ? $STUD_PART3_FROM_DT : NULL;
			
			$STUD_PART3_TO_DT = $row['STUD_PART3_TO_DT'];
			$STUD_PART3_TO_DT = !empty($STUD_PART3_TO_DT) ? $STUD_PART3_TO_DT : NULL;
			
			$STUD_PART1_WEF = $row['STUD_PART1_WEF'];
			$STUD_PART1_WEF = !empty($STUD_PART1_WEF) ? $STUD_PART1_WEF : NULL;
						
			$STUD_PART3_DT = $row['STUD_PART3_DT'];
			$STUD_PART3_DT = !empty($STUD_PART3_DT) ? $STUD_PART3_DT : NULL;
			
			$sql2 = "INSERT INTO t_form_109 SET 
			STUD_PART1_MEMBER_I =:STUD_PART1_MEMBER_I, STUD_PART1_MEMBER_MS =:STUD_PART1_MEMBER_MS, STUD_PART1_TRAINEE_NAME =:STUD_PART1_TRAINEE_NAME, STUD_PART1_PERIOD_DD =:STUD_PART1_PERIOD_DD, STUD_PART1_PERIO_MM =:STUD_PART1_PERIO_MM, STUD_PART1_PERIOD_YY =:STUD_PART1_PERIOD_YY, STUD_PART1_FROM_DT =:STUD_PART1_FROM_DT, STUD_PART1_TO_DT =:STUD_PART1_TO_DT, STUD_PART1_TERMINATED_DT =:STUD_PART1_TERMINATED_DT, STUD_PART1_TERMINATED_LEAVE =:STUD_PART1_TERMINATED_LEAVE, STUD_PART1_ACCOUNT_NO =:STUD_PART1_ACCOUNT_NO, STUD_PART1_ACCOUNT_WITH =:STUD_PART1_ACCOUNT_WITH, STUD_PART1_ACCOUNT_BANK =:STUD_PART1_ACCOUNT_BANK, STUD_PART1_VIDE_REGISTRATION =:STUD_PART1_VIDE_REGISTRATION, STUD_PART1_MEMBER_NO =:STUD_PART1_MEMBER_NO, STUD_PART1_MEMBER_NAME =:STUD_PART1_MEMBER_NAME, STUD_PART1_TRAINEE_I =:STUD_PART1_TRAINEE_I, STUD_PART1_MEMBER_NAME2 =:STUD_PART1_MEMBER_NAME2, STUD_PART1_WEF =:STUD_PART1_WEF, STUD_PART3_REGISTRATION_NO =:STUD_PART3_REGISTRATION_NO, STUD_PART3_TRAINEE_NAME =:STUD_PART3_TRAINEE_NAME, STUD_PART3_COMMENCEMENT_DT =:STUD_PART3_COMMENCEMENT_DT, STUD_PART3_MEMBER_INCHARGE =:STUD_PART3_MEMBER_INCHARGE, STUD_PART3_INCHARGE_MEMBERSHIP =:STUD_PART3_INCHARGE_MEMBERSHIP, STUD_PART3_PRINCIPLE =:STUD_PART3_PRINCIPLE, STUD_PART3_PRINCIPLE_MEMBERSHIP =:STUD_PART3_PRINCIPLE_MEMBERSHIP, STUD_PART3_ORGANIZATION_NAME =:STUD_PART3_ORGANIZATION_NAME, STUD_PART3_FIRM_NO =:STUD_PART3_FIRM_NO, STUD_PART3_FROM_DT =:STUD_PART3_FROM_DT, STUD_PART3_TO_DT =:STUD_PART3_TO_DT, STUD_PART3_ACCOUNTING_1 =:STUD_PART3_ACCOUNTING_1, STUD_PART3_ACCOUNTING_2 =:STUD_PART3_ACCOUNTING_2, STUD_PART3_ACCOUNTING_3 =:STUD_PART3_ACCOUNTING_3, STUD_PART3_AUDITING_1 =:STUD_PART3_AUDITING_1, STUD_PART3_AUDITING_2 =:STUD_PART3_AUDITING_2, STUD_PART3_AUDITING_3 =:STUD_PART3_AUDITING_3, STUD_PART3_TAXATION_1 =:STUD_PART3_TAXATION_1, STUD_PART3_TAXATION_2 =:STUD_PART3_TAXATION_2, STUD_PART3_TAXATION_3 =:STUD_PART3_TAXATION_3, STUD_PART3_IT_1 =:STUD_PART3_IT_1, STUD_PART3_IT_2 =:STUD_PART3_IT_2, STUD_PART3_IT_3 =:STUD_PART3_IT_3, STUD_PART3_MCOS_1 =:STUD_PART3_MCOS_1, STUD_PART3_MCOS_2 =:STUD_PART3_MCOS_2, STUD_PART3_MCOS_3 =:STUD_PART3_MCOS_3, STUD_PART3_OTHER_1 =:STUD_PART3_OTHER_1, STUD_PART3_OTHER_2 =:STUD_PART3_OTHER_2, STUD_PART3_OTHER_3 =:STUD_PART3_OTHER_3, STUD_PART3_PARTICULAR_1 =:STUD_PART3_PARTICULAR_1, STUD_PART3_PARTICULAR_HR_1 =:STUD_PART3_PARTICULAR_HR_1, STUD_PART3_PARTICULAR_2 =:STUD_PART3_PARTICULAR_2, STUD_PART3_PARTICULAR_HR_2 =:STUD_PART3_PARTICULAR_HR_2, STUD_PART3_PARTICULAR_3 =:STUD_PART3_PARTICULAR_3, STUD_PART3_PARTICULAR_HR_3 =:STUD_PART3_PARTICULAR_HR_3, STUD_PART3_COMMENT =:STUD_PART3_COMMENT, MRH_MRN =:MRH_MRN, FORM_SAVE_STATUS =:FORM_SAVE_STATUS, TERMINATE_CONTROL_NO =:TERMINATE_CONTROL_NO, User_IP =:User_IP, STUD_PDF_PATH =:STUD_PDF_PATH, FORM_SUBMIT_DT =:FORM_SUBMIT_DT, STUD_REGION_CODE =:STUD_REGION_CODE, Post_BY_Cloud =:Post_BY_Cloud, Post_BY_Cloud_date =:Post_BY_Cloud_date, STUD_PART3_PLACE =:STUD_PART3_PLACE, STUD_PART3_DT =:STUD_PART3_DT";
			
			
			$stmt2 = $conn4->prepare($sql2);
			$stmt2->bindValue(':STUD_PART1_MEMBER_I', $row['STUD_PART1_MEMBER_I']);  
			$stmt2->bindValue(':STUD_PART1_MEMBER_MS', $row['STUD_PART1_MEMBER_MS']);
			$stmt2->bindValue(':STUD_PART1_TRAINEE_NAME', $row['STUD_PART1_TRAINEE_NAME']);
			$stmt2->bindValue(':STUD_PART1_PERIOD_DD', $row['STUD_PART1_PERIOD_DD']);
			$stmt2->bindValue(':STUD_PART1_PERIO_MM', $row['STUD_PART1_PERIO_MM']);
			$stmt2->bindValue(':STUD_PART1_PERIOD_YY', $row['STUD_PART1_PERIOD_YY']);
			$stmt2->bindValue(':STUD_PART1_FROM_DT', $STUD_PART1_FROM_DT);
			$stmt2->bindValue(':STUD_PART1_TO_DT', $STUD_PART1_TO_DT);
			$stmt2->bindValue(':STUD_PART1_TERMINATED_DT', $STUD_PART1_TERMINATED_DT);
			$stmt2->bindValue(':STUD_PART1_TERMINATED_LEAVE', $row['STUD_PART1_TERMINATED_LEAVE']);
			$stmt2->bindValue(':STUD_PART1_ACCOUNT_NO', $row['STUD_PART1_ACCOUNT_NO']);
			$stmt2->bindValue(':STUD_PART1_ACCOUNT_WITH', $row['STUD_PART1_ACCOUNT_WITH']);
			$stmt2->bindValue(':STUD_PART1_ACCOUNT_BANK', $row['STUD_PART1_ACCOUNT_BANK']);
			$stmt2->bindValue(':STUD_PART1_VIDE_REGISTRATION', $row['STUD_PART1_VIDE_REGISTRATION']);
			$stmt2->bindValue(':STUD_PART1_MEMBER_NO', $row['STUD_PART1_MEMBER_NO']);
			$stmt2->bindValue(':STUD_PART1_MEMBER_NAME', $row['STUD_PART1_MEMBER_NAME']);
			$stmt2->bindValue(':STUD_PART1_TRAINEE_I', $row['STUD_PART1_TRAINEE_I']);
			$stmt2->bindValue(':STUD_PART1_MEMBER_NAME2', $row['STUD_PART1_MEMBER_NAME2']);
			$stmt2->bindValue(':STUD_PART1_WEF', $STUD_PART1_WEF);
			$stmt2->bindValue(':STUD_PART3_REGISTRATION_NO', $row['STUD_PART3_REGISTRATION_NO']);
			$stmt2->bindValue(':STUD_PART3_TRAINEE_NAME', $row['STUD_PART3_TRAINEE_NAME']);
			$stmt2->bindValue(':STUD_PART3_COMMENCEMENT_DT', $STUD_PART3_COMMENCEMENT_DT);
			$stmt2->bindValue(':STUD_PART3_MEMBER_INCHARGE', $row['STUD_PART3_MEMBER_INCHARGE']);
			$stmt2->bindValue(':STUD_PART3_INCHARGE_MEMBERSHIP', $row['STUD_PART3_INCHARGE_MEMBERSHIP']);
			$stmt2->bindValue(':STUD_PART3_PRINCIPLE', $row['STUD_PART3_PRINCIPLE']);
			$stmt2->bindValue(':STUD_PART3_PRINCIPLE_MEMBERSHIP', $row['STUD_PART3_PRINCIPLE_MEMBERSHIP']);
			$stmt2->bindValue(':STUD_PART3_ORGANIZATION_NAME', $row['STUD_PART3_ORGANIZATION_NAME']);
			$stmt2->bindValue(':STUD_PART3_FIRM_NO', $row['STUD_PART3_FIRM_NO']);
			$stmt2->bindValue(':STUD_PART3_FROM_DT', $STUD_PART3_FROM_DT);
			$stmt2->bindValue(':STUD_PART3_TO_DT', $STUD_PART3_TO_DT);
			$stmt2->bindValue(':STUD_PART3_ACCOUNTING_1', $row['STUD_PART3_ACCOUNTING_1']);
			$stmt2->bindValue(':STUD_PART3_ACCOUNTING_2', $row['STUD_PART3_ACCOUNTING_2']);
			$stmt2->bindValue(':STUD_PART3_ACCOUNTING_3', $row['STUD_PART3_ACCOUNTING_3']);
			$stmt2->bindValue(':STUD_PART3_AUDITING_1', $row['STUD_PART3_AUDITING_1']);
			$stmt2->bindValue(':STUD_PART3_AUDITING_2', $row['STUD_PART3_AUDITING_2']);
			$stmt2->bindValue(':STUD_PART3_AUDITING_3', $row['STUD_PART3_AUDITING_3']);
			$stmt2->bindValue(':STUD_PART3_TAXATION_1', $row['STUD_PART3_TAXATION_1']);
			$stmt2->bindValue(':STUD_PART3_TAXATION_2', $row['STUD_PART3_TAXATION_2']);
			$stmt2->bindValue(':STUD_PART3_TAXATION_3', $row['STUD_PART3_TAXATION_3']);
			$stmt2->bindValue(':STUD_PART3_IT_1', $row['STUD_PART3_IT_1']);
			$stmt2->bindValue(':STUD_PART3_IT_2', $row['STUD_PART3_IT_2']);
			$stmt2->bindValue(':STUD_PART3_IT_3', $row['STUD_PART3_IT_3']);
			$stmt2->bindValue(':STUD_PART3_MCOS_1', $row['STUD_PART3_MCOS_1']);
			$stmt2->bindValue(':STUD_PART3_MCOS_2', $row['STUD_PART3_MCOS_2']);
			$stmt2->bindValue(':STUD_PART3_MCOS_3', $row['STUD_PART3_MCOS_3']);
			$stmt2->bindValue(':STUD_PART3_OTHER_1', $row['STUD_PART3_OTHER_1']);
			$stmt2->bindValue(':STUD_PART3_OTHER_2', $row['STUD_PART3_OTHER_2']);
			$stmt2->bindValue(':STUD_PART3_OTHER_3', $row['STUD_PART3_OTHER_3']);
			$stmt2->bindValue(':STUD_PART3_PARTICULAR_1', $row['STUD_PART3_PARTICULAR_1']);
			$stmt2->bindValue(':STUD_PART3_PARTICULAR_HR_1', $row['STUD_PART3_PARTICULAR_HR_1']);
			$stmt2->bindValue(':STUD_PART3_PARTICULAR_2', $row['STUD_PART3_PARTICULAR_2']);
			$stmt2->bindValue(':STUD_PART3_PARTICULAR_HR_2', $row['STUD_PART3_PARTICULAR_HR_2']);
			$stmt2->bindValue(':STUD_PART3_PARTICULAR_3', $row['STUD_PART3_PARTICULAR_3']);
			$stmt2->bindValue(':STUD_PART3_PARTICULAR_HR_3', $row['STUD_PART3_PARTICULAR_HR_3']);
			$stmt2->bindValue(':STUD_PART3_COMMENT', $row['STUD_PART3_COMMENT']);
			$stmt2->bindValue(':MRH_MRN', $row['MRH_MRN']);
			$stmt2->bindValue(':FORM_SAVE_STATUS', $row['FORM_SAVE_STATUS']);
			$stmt2->bindValue(':TERMINATE_CONTROL_NO', $row['TERMINATE_CONTROL_NO']);
			$stmt2->bindValue(':User_IP', $row['User_IP']);
			$stmt2->bindValue(':STUD_PDF_PATH', $row['STUD_PDF_PATH']);
			$stmt2->bindValue(':FORM_SUBMIT_DT', $row['FORM_SUBMIT_DT']);
			$stmt2->bindValue(':STUD_REGION_CODE', $row['STUD_REGION_CODE']);
			$stmt2->bindValue(':Post_BY_Cloud', 'Y');
			$stmt2->bindValue(':Post_BY_Cloud_date', date('Y-m-d'));
			$stmt2->bindValue(':STUD_PART3_PLACE', $row['STUD_PART3_PLACE']);
			$stmt2->bindValue(':STUD_PART3_DT', $STUD_PART3_DT);
			
			
					
			$res = $stmt2->execute();	
			if($res === false){
				$error = $stmt2->errorInfo();
				//print_r($error);die;
				file_put_contents('error_log.txt', 'Date : '.date('d-m-Y h:i:s').' ::'.$error[2].' for '.$MRH_MRN.PHP_EOL, FILE_APPEND);
			}else{
				change_post_status_form109($row['MRH_MRN'], $row['FORM_NO']);	
			}
						
			
			}			  
		}				  
	}else{			
		echo "NO connection with delhi server";
	}
} */


/******************* CHANGE POST STATUS START ***************/
/* function change_post_status_form109($MRH_MRN, $FORM_NO){	
	global $conn2;
	
	$result2 = $conn2->query("SET NAMES utf8");
	$stmt = $conn2->prepare("UPDATE t_form_109 SET Post_BY_Cloud='Y' ,Post_BY_Cloud_date=now()  WHERE FORM_NO = ? AND MRH_MRN =? ");
	$stmt->bindValue(1,$FORM_NO);
	$stmt->bindValue(2,$MRH_MRN);	
	$stmt->execute();					
} */
/******************* CHANGE POST STATUS END ***************/

}
catch(Exception $e){
	$error_text = $e->getMessage();
	//echo $e->getMessage();
	file_put_contents('error_log.txt', $error_text."\r\n", FILE_APPEND);	
}

/* ****************************End**************************************************** */

/*********************** ACK MAX NO CALCULATE START ***************/
function ACKR_ControlNo_New_18($form_number){	  
	global $conn2;
	$result = $conn2->query("SET NAMES utf8");
	
	if($form_number == 'form_103'){	   
		$sql ="SELECT case when max(CONVERT(right(ARTICLED_CONTROL_NO, 8), SIGNED INTEGER))='' or 		max(CONVERT(right(ARTICLED_CONTROL_NO, 8), SIGNED INTEGER)) is null then 0 else max(CONVERT(right(ARTICLED_CONTROL_NO, 8), SIGNED INTEGER)) end as control_no FROM t_".$form_number." t where STUD_TRANS_ID<>'' and STUD_TRANS_RESPONSE='Approved' and STUD_TRANS_STATUS='Transaction Successful'";		
	}else if($form_number == 'form_103_re'){
		$sql ="SELECT case when max(CONVERT(right(ARTICLED_CONTROL_NO, 8), SIGNED INTEGER))='' or 		max(CONVERT(right(ARTICLED_CONTROL_NO, 8), SIGNED INTEGER)) is null then 0 else max(CONVERT(right(ARTICLED_CONTROL_NO, 8), SIGNED INTEGER)) end as control_no FROM t_".$form_number." t where STUD_TRANS_ID<>'' and STUD_TRANS_RESPONSE='Approved' and STUD_TRANS_STATUS='Transaction Successful'";
	}else if($form_number == 'form_109'){
		$sql ="SELECT case when max(CONVERT(right(TERMINATE_CONTROL_NO, 8), SIGNED INTEGER))='' or 		max(CONVERT(right(TERMINATE_CONTROL_NO, 8), SIGNED INTEGER)) is null then 0 else max(CONVERT(right(TERMINATE_CONTROL_NO, 8), SIGNED INTEGER)) end as control_no FROM t_".$form_number." t";
	}	
	$stmt = $conn2->prepare($sql);			 
	$stmt->execute();
	$result=$stmt->fetchAll();
		if (count($result) > 0) {		     
		return $result[0] ;	  
	}		
}
/*********************** ACK MAX NO CALCULATE END ***************/



// ADDED BY VARUN 30 AUG 
function insert_payment_info_form18($form_number,$MRH_MRN,$paid_amount,$payment_date,$transaction_response_code,$transaction_response_code_desc,$receipt_number,$transaction_number,$transaction_message,$m05,$m06,$m07,$m11,$m12,$FORM_ID)
{
        // echo "11";
        global $conn2;
		$form_username= $_SESSION['UserID'] ;
		$year=date('Y');
	    $sql = "INSERT INTO  om_member_payment_info SET   form_number='".$form_number."', MRH_MRN='".$MRH_MRN."', paid_amount=".$paid_amount.", payment_date='".$payment_date."', transaction_response_code='".$transaction_response_code."', transaction_response_code_desc='".$transaction_response_code_desc."', receipt_number='".$receipt_number."', transaction_number='".$transaction_number."', transaction_message='".$transaction_message."', m05='".$m05."', m06='".$m06."', m07='".$m07."', m11='".$m11."', m12='".$m12."',Paid_for_year='".$year."',RESTORATION_CONTROL_NO='' ";
		//echo "<pre>"; print_r($sql);die;
		  // Prepare statement
        $stmt = $conn2->prepare($sql);
         // execute the query
        $stmt->execute();
		
		if($transaction_response_code=='0' && $transaction_number!='' && $transaction_message == 'Approved' && $transaction_response_code_desc == 'Transaction Successful')
		{
			
			$result4 = $conn2->query("SET NAMES utf8");	  		 
			$stmt = $conn2->prepare("SELECT * FROM t_form_18 WHERE MRH_TRANS_RESPONSE='Approved' AND MRH_TRANS_STATUS='Transaction Successful' AND MRH_MRN = ? AND FORM_NO = ?");
		 
			$stmt->bindValue(1,$MRH_MRN);		 
			$stmt->bindValue(2,$FORM_ID);		 
			$stmt->execute();
			$result4=$stmt->fetchAll();
				if (count($result4) == 0) {	

					$ACKR_CONTROL_MAX_NO=ACKR_ControlNo_allform($form_number);
					$NAME_RESTORING_CONTROL_NO='ACKCCP'.str_pad($ACKR_CONTROL_MAX_NO['control_no']+1, 7, "0", STR_PAD_LEFT);
					
					$sql2 = "UPDATE t_form_18 SET  MRH_TRANS_TOTAL_AMT=".$paid_amount.", MRH_TRANS_DATE='".$payment_date."',   MRH_TRANS_STATUS='".$transaction_response_code_desc."', MRH_TRANS_ID='".$transaction_number."', MRH_TRANS_RESPONSE='".$transaction_message."',NAME_RESTORING_CONTROL_NO='".$NAME_RESTORING_CONTROL_NO."' WHERE  MRH_MRN='".$MRH_MRN."' AND FORM_ID = '".$FORM_ID."'";
					
					// Prepare statement
					$stmt2 = $conn2->prepare($sql2);
					// execute the query
					$stmt2->execute();
					
					trans_data_to_delhi_new_form18($MRH_MRN, $FORM_ID); // TRANSFER DATA TO DELHI SERVER 
					
					
					
					/**********************End***************************************************/
				}		
		}
		
    // echo a message to say the UPDATE succeeded
       return $sql;
	
}
/*  ***************************form18 15 april *************************************/


function calculate_fee_form18_re($FORMATION_PROPRIETORY_DATE){
global $conn2;
$fee = array();

if($FORMATION_PROPRIETORY_DATE != '' && $FORMATION_PROPRIETORY_DATE != '0000-00-00'){

$current_date = date('Y-m-d');
$FORMATION_PROPRIETORY_DATE = new DateTime($FORMATION_PROPRIETORY_DATE);
$current_date = new DateTime($current_date);
$days_from_current_date = $FORMATION_PROPRIETORY_DATE->diff($current_date)->format("%r%a");
if($days_from_current_date > 30 && $days_from_current_date <= 60){
$fee['DELAY_FEE'] = 100;
}elseif($days_from_current_date > 60 && $days_from_current_date <= 180){
$fee['DELAY_FEE'] = 300;
}elseif($days_from_current_date > 180){
$fee['DELAY_FEE'] = 1000;
}else{
$fee['DELAY_FEE'] = 0;
}

}

//$fee['S109'] = 1000;
//$fee['S110'] = 1000;
$fee['TOTAL_AMT'] = $fee['DELAY_FEE'];
//print_r($fee);die;
return $fee;

}



/*  ******************************Form 18 Transfer Data by varaun****************************************  */
function trans_data_to_delhi_new_form18($form_username, $FORM_NO)
{      
include('dbconnect_delhi.php');
        global $conn2;
		global $conn4;
		global $wwwroot;
		
		if($conn4){
       
	      $result4 = $conn2->query("SET NAMES utf8");	  
		  $stmt = $conn2->prepare("SELECT * FROM t_form_18 WHERE MRH_MRN =?  AND FORM_NO = ? ");
		  //$stmt->bindValue(1,$form_username);	

          $stmt->bindValue(1,$form_username);			  
		  $stmt->bindValue(2,$FORM_NO);		 
		  $stmt->execute();
		  $result2=$stmt->fetchAll();
		  
		  if (count($result2) > 0) {
			 
		    $row=$result2[0]   ;
			$NAME_RESTORING_CONTROL_NO = $row['NAME_RESTORING_CONTROL_NO'];
			 
			if  ($row['CERTIFICATE_DATE_1']=="")
			{$CERTIFICATE_DATE_1="0000-00-00";
			}
			else{ $CERTIFICATE_DATE_1=$row['CERTIFICATE_DATE_1'] ;}
			
			if  ($row['CERTIFICATE_DATE_2']=="")
			{$CERTIFICATE_DATE_2="0000-00-00";
			}
			else{ $CERTIFICATE_DATE_2=$row['CERTIFICATE_DATE_2'] ;}
			
			if  ($row['CERTIFICATE_DATE_3']=="")
			{$CERTIFICATE_DATE_3="0000-00-00";
			}
			else{ $CERTIFICATE_DATE_3=$row['CERTIFICATE_DATE_3'] ;}
			
			if  ($row['CERTIFICATE_DATE_4']=="")
			{$CERTIFICATE_DATE_4="0000-00-00";
			}
			else{ $CERTIFICATE_DATE_4=$row['CERTIFICATE_DATE_4'] ;}
			
			if  ($row['CERTIFICATE_DATE_5']=="")
			{$CERTIFICATE_DATE_5="0000-00-00";
			}
			else{ $CERTIFICATE_DATE_5=$row['CERTIFICATE_DATE_5'] ;}
			
			if  ($row['CERTIFICATE_DATE_6']=="")
			{$CERTIFICATE_DATE_6="0000-00-00";
			}
			else{ $CERTIFICATE_DATE_6=$row['CERTIFICATE_DATE_6'] ;}
			
			if  ($row['FORMATION_PROPRIETORY_DATE']=="")
			{$FORMATION_PROPRIETORY_DATE="0000-00-00";
			}
			else{ $FORMATION_PROPRIETORY_DATE=$row['FORMATION_PROPRIETORY_DATE'] ;}
			
			if  ($row['PRESENT_PARTNERSHIP_DATE']=="")
			{$PRESENT_PARTNERSHIP_DATE="0000-00-00";
			}
			else{ $PRESENT_PARTNERSHIP_DATE=$row['PRESENT_PARTNERSHIP_DATE'] ;}
			
			if  ($row['DATE_OF_BRANCH_1']=="")
			{$DATE_OF_BRANCH_1="0000-00-00";
			}
			else{ $DATE_OF_BRANCH_1=$row['DATE_OF_BRANCH_1'] ;}
			
			if  ($row['DATE_OF_BRANCH_2']=="")
			{$DATE_OF_BRANCH_2="0000-00-00";
			}
			else{ $DATE_OF_BRANCH_2=$row['DATE_OF_BRANCH_2'] ;}
			
			if  ($row['$DATE_OF_BRANCH_3']=="")
			{$DATE_OF_BRANCH_3="0000-00-00";
			}
			else{ $DATE_OF_BRANCH_3=$row['DATE_OF_BRANCH_3'] ;}
			
			if  ( $row['DATE_OF_BRANCH_4'] == "" )
			{$DATE_OF_BRANCH_4="0000-00-00";
			}
			else{ $DATE_OF_BRANCH_4=$row['DATE_OF_BRANCH_4'] ;}
			
			
			if  ($row['DATE_OF_BRANCH_5']=="")
			{$DATE_OF_BRANCH_5="0000-00-00";
			}
			else{ $DATE_OF_BRANCH_5=$row['DATE_OF_BRANCH_5'] ;}
			
			
			
			if  ($row['INS_MEM_DOJ_LINE_1']=="")
			{$INS_MEM_DOJ_LINE_1="0000-00-00";
			}
			else{ $INS_MEM_DOJ_LINE_1=$row['INS_MEM_DOJ_LINE_1'] ;}
			
			if  ($row['INS_MEM_DOJ_LINE_2']=="")
			{$INS_MEM_DOJ_LINE_2="0000-00-00";
			}
			else{ $INS_MEM_DOJ_LINE_2=$row['INS_MEM_DOJ_LINE_2'] ;}
			
			if  ($row['INS_MEM_DOJ_LINE_3']=="")
			{$INS_MEM_DOJ_LINE_3="0000-00-00";
			}
			else{ $INS_MEM_DOJ_LINE_3=$row['INS_MEM_DOJ_LINE_3'] ;}
			
			if  ($row['INS_MEM_DOJ_LINE_4']=="")
			{$INS_MEM_DOJ_LINE_4="0000-00-00";
			}
			else{ $INS_MEM_DOJ_LINE_4=$row['INS_MEM_DOJ_LINE_4'] ;}
			
			if  ($row['INS_MEM_DOJ_LINE_5']=="")
			{$INS_MEM_DOJ_LINE_5="0000-00-00";
			}
			else{ $INS_MEM_DOJ_LINE_5=$row['INS_MEM_DOJ_LINE_5'] ;}
			
			if  ($row['INDIVISUAL_PA_MEM_DATE']=="")
			{$INDIVISUAL_PA_MEM_DATE="0000-00-00";
			}
			else{ $INDIVISUAL_PA_MEM_DATE=$row['INDIVISUAL_PA_MEM_DATE'] ;}
			
			
			
			$stmt3 = $conn4->prepare("SELECT MRH_MRN FROM t_form_18 WHERE MRH_MRN= ? AND NAME_RESTORING_CONTROL_NO = ?" );
			 // $stmt3->bindValue(1,$form_username);
			 
			 $stmt3->bindValue(1,$form_username);
			  $stmt3->bindValue(2,$NAME_RESTORING_CONTROL_NO);
		      $stmt3->execute();
		      $result3=$stmt3->fetchAll();
		      if (count($result3) > 0) { 
			    
				echo "Data Already Imported";
			  
			  }else{
				   //echo "akal2323232332";
			 $sql2 = "INSERT INTO t_form_18 SET 
			 PROPRIETOR_PARTNER='".$row['PROPRIETOR_PARTNER']."',
			 PROPRIETOR_PARTNER_NAME='".$row['PROPRIETOR_PARTNER_NAME']."',
			 PROPRIETOR_NAME_1='".$row['PROPRIETOR_NAME_1']."',
			 MEMBERSHIP_NUMBER_1='".$row['MEMBERSHIP_NUMBER_1']."',
			 CERTIFICATE_DATE_1='".$row['CERTIFICATE_DATE_1']."',
			 PARTNER_NAME_2='".$row['PARTNER_NAME_2']."', 
			 MEMBERSHIP_NUMBER_2='".$row['MEMBERSHIP_NUMBER_2']."',
			 CERTIFICATE_DATE_2='".$row['CERTIFICATE_DATE_2']."',
			 PARTNER_NAME_3='".$row['PARTNER_NAME_3']."',
			 MEMBERSHIP_NUMBER_3='".$row['MEMBERSHIP_NUMBER_3']."', 
			 CERTIFICATE_DATE_3='".$row['CERTIFICATE_DATE_3']."',
			 PARTNER_NAME_4='".$row['PARTNER_NAME_4']."',
			 MEMBERSHIP_NUMBER_4='".$row['MEMBERSHIP_NUMBER_4']."',
			 CERTIFICATE_DATE_4='".$row['CERTIFICATE_DATE_4']."',
			 PARTNER_NAME_5='".$row['PARTNER_NAME_5']."', 
			 MEMBERSHIP_NUMBER_5='".$row['MEMBERSHIP_NUMBER_5']."',
			 CERTIFICATE_DATE_5='".$row['CERTIFICATE_DATE_5']."', 
			 PARTNER_NAME_6='".$row['PARTNER_NAME_6']."',
			 MEMBERSHIP_NUMBER_6='".$row['MEMBERSHIP_NUMBER_6']."', 
			 CERTIFICATE_DATE_6='".$row['CERTIFICATE_DATE_6']."',
			 
			 FORMATION_PROPRIETORY_DATE='".$FORMATION_PROPRIETORY_DATE."',
			 PRESENT_PARTNERSHIP_DATE='".$PRESENT_PARTNERSHIP_DATE."',
			 PARTNERSHIP_STATUS='".$row['PARTNERSHIP_STATUS']."',
			 PARTNER_SHARE_STATUS='".$row['PARTNER_SHARE_STATUS']."',
			 DATE_PARTICULARS_APPROVAL='".$row['DATE_PARTICULARS_APPROVAL']."',
			 FIRM_NAME='".$row['FIRM_NAME']."',
			 ADD_HEAD_OFFICE_LINE_1='".$row['ADD_HEAD_OFFICE_LINE_1']."',
			 ADD_HEAD_OFFICE_LINE_2='".$row['ADD_HEAD_OFFICE_LINE_2']."',
			 ADD_HEAD_OFFICE_LINE_3='".$row['ADD_HEAD_OFFICE_LINE_3']."',
			 ADD_HEAD_OFFICE_LINE_4='".$row['ADD_HEAD_OFFICE_LINE_4']."',
			 HEAD_OFFICE_CITY_CODE='".$row['HEAD_OFFICE_CITY_CODE']."',
			 HEAD_OFFICE_STATE_CODE='".$row['HEAD_OFFICE_STATE_CODE']."',
			 HEAD_OFFICE_ZIP_POSTAL_CODE='".$row['HEAD_OFFICE_ZIP_POSTAL_CODE']."', 
			 HEAD_OFFICE_TEL='".$row['HEAD_OFFICE_TEL']."',
			 HEAD_OFFICE_COU_CODE='".$row['HEAD_OFFICE_COU_CODE']."',
			 HEAD_OFFICE_EMAIL='".$row['HEAD_OFFICE_EMAIL']."',
			 HEAD_OFFICE_MOBILE='".$row['HEAD_OFFICE_MOBILE']."',
			 SIX_MRH_RES_ADDR_LINE_1='".$row['SIX_MRH_RES_ADDR_LINE_1']."',
			 SIX_MRH_RES_ADDR_LINE_2='".$row['SIX_MRH_RES_ADDR_LINE_2']."',
			 SIX_MRH_RES_ADDR_LINE_3='".$row['SIX_MRH_RES_ADDR_LINE_3']."',
			 SIX_MRH_RES_ADDR_LINE_4='".$row['SIX_MRH_RES_ADDR_LINE_4']."',
			 SIX_MRH_RES_CITY_CODE='".$row['SIX_MRH_RES_CITY_CODE']."',
			 SIX_MRH_RES_STATE_CODE='".$row['SIX_MRH_RES_STATE_CODE']."',
			 SIX_MRH_RES_ZIP_POSTAL_CODE='".$row['SIX_MRH_RES_ZIP_POSTAL_CODE']."',
			 SIX_MRH_RES_TEL='".$row['SIX_MRH_RES_TEL']."',
			 SIX_MRH_RES_COU_CODE='".$row['SIX_MRH_RES_COU_CODE']."',
			 SIX_MRH_RES_EMAIL='".$row['SIX_MRH_RES_EMAIL']."',
			 SIX_MRH_RES_MOBILE='".$row['SIX_MRH_RES_MOBILE']."',
			 SIX_TWO_MRH_RES_ADDR_LINE_1='".$row['SIX_TWO_MRH_RES_ADDR_LINE_1']."',
			 SIX_TWO_MRH_RES_ADDR_LINE_2='".$row['SIX_TWO_MRH_RES_ADDR_LINE_2']."',
			 SIX_TWO_MRH_RES_ADDR_LINE_3='".$row['SIX_TWO_MRH_RES_ADDR_LINE_3']."',
			 SIX_TWO_MRH_RES_ADDR_LINE_4='".$row['SIX_TWO_MRH_RES_ADDR_LINE_4']."',
			 SIX_TWO_MRH_RES_CITY_CODE='".$row['SIX_TWO_MRH_RES_CITY_CODE']."',
			 SIX_TWO_MRH_RES_STATE_CODE='".$row['SIX_TWO_MRH_RES_STATE_CODE']."', 
			 SIX_TWO_MRH_RES_ZIP_POSTAL_CODE='".$row['SIX_TWO_MRH_RES_ZIP_POSTAL_CODE']."',
			 SIX_TWO_MRH_RES_TEL='".$row['SIX_TWO_MRH_RES_TEL']."',
			 SIX_TWO_MRH_RES_COU_CODE='".$row['SIX_TWO_MRH_RES_COU_CODE']."',
			 SIX_TWO_MRH_RES_EMAIL='".$row['SIX_TWO_MRH_RES_EMAIL']."',
			 SIX_TWO_MRH_RES_MOBILE='".$row['SIX_TWO_MRH_RES_MOBILE']."',
			 SIX_THREE_MRH_RES_ADDR_LINE_1='".$row['SIX_THREE_MRH_RES_ADDR_LINE_1']."',
			 SIX_THREE_MRH_RES_ADDR_LINE_2='".$row['SIX_THREE_MRH_RES_ADDR_LINE_2']."',
			 SIX_THREE_MRH_RES_ADDR_LINE_3='".$row['SIX_THREE_MRH_RES_ADDR_LINE_3']."',
			 SIX_THREE_MRH_RES_ADDR_LINE_4='".$row['SIX_THREE_MRH_RES_ADDR_LINE_4']."',
			 SIX_THREE_MRH_RES_CITY_CODE='".$row['SIX_THREE_MRH_RES_CITY_CODE']."', 
			 SIX_THREE_MRH_RES_STATE_CODE='".$row['SIX_THREE_MRH_RES_STATE_CODE']."',
			 SIX_THREE_MRH_RES_ZIP_POSTAL_CODE='".$row['SIX_THREE_MRH_RES_ZIP_POSTAL_CODE']."', 
			 SIX_THREE_MRH_RES_TEL='".$row['SIX_THREE_MRH_RES_TEL']."', 
			 SIX_THREE_MRH_RES_COU_CODE='".$row['SIX_THREE_MRH_RES_COU_CODE']."',
			 SIX_THREE_MRH_RES_EMAIL='".$row['SIX_THREE_MRH_RES_EMAIL']."',
			 SIX_THREE_MRH_RES_MOBILE='".$row['SIX_THREE_MRH_RES_MOBILE']."',
			 PLACE_OF_BRANCH_1='".$row['PLACE_OF_BRANCH_1']."',
			 DATE_OF_BRANCH_1='".$DATE_OF_BRANCH_1."',
			 PLACE_OF_BRANCH_2='".$row['PLACE_OF_BRANCH_2']."', 
			 DATE_OF_BRANCH_2='".$DATE_OF_BRANCH_2."',
			 PLACE_OF_BRANCH_3='".$row['PLACE_OF_BRANCH_3']."',
			 DATE_OF_BRANCH_3='".$DATE_OF_BRANCH_3."',
			 PLACE_OF_BRANCH_4='".$row['PLACE_OF_BRANCH_4']."',
			 DATE_OF_BRANCH_4='".$DATE_OF_BRANCH_4."',
			 PLACE_OF_BRANCH_5='".$row['PLACE_OF_BRANCH_5']."',
			 DATE_OF_BRANCH_5='".$DATE_OF_BRANCH_5."',
			 BRANCH_OFFICE='".$row['BRANCH_OFFICE']."', 
			 MEMBER_IN_CHARGE='".$row['MEMBER_IN_CHARGE']."',
			 MEMBER_NUMBER='".$row['MEMBER_NUMBER']."',
			 BRANCH_OFFICE_1='".$row['BRANCH_OFFICE_1']."',
			 MEMBER_IN_CHARGE_1='".$row['MEMBER_IN_CHARGE_1']."', 
			 MEMBER_NUMBER_1='".$row['MEMBER_NUMBER_1']."', 
			 BRANCH_OFFICE_2='".$row['BRANCH_OFFICE_2']."', 
			 MEMBER_IN_CHARGE_2='".$row['MEMBER_IN_CHARGE_2']."',
			 MEMBER_NUMBER_2='".$row['MEMBER_NUMBER_2']."', 
			 BRANCH_OFFICE_3='".$row['BRANCH_OFFICE_3']."', 
			 MEMBER_IN_CHARGE_3='".$row['MEMBER_IN_CHARGE_3']."',
			 MEMBER_NUMBER_3='".$row['MEMBER_NUMBER_3']."',
			 BRANCH_OFFICE_4='".$row['BRANCH_OFFICE_4']."',
			 MEMBER_IN_CHARGE_4='".$row['MEMBER_IN_CHARGE_4']."', 
			 MEMBER_NUMBER_4='".$row['MEMBER_NUMBER_4']."',
			 MRH_PRO_PARTNER='".$row['MRH_PRO_PARTNER']."',
			 PAR_PRO_PA_NAME='".$row['PAR_PRO_PA_NAME']."', 
			 CA_FIRM_NAME='".$row['CA_FIRM_NAME']."',
			 CAPACITY_CONNECTED='".$row['CAPACITY_CONNECTED']."',
			 OCCUPATION_DETAILS='".$row['OCCUPATION_DETAILS']."',
			 PAR_PRO_PA_NAME_1='".$row['PAR_PRO_PA_NAME_1']."',
			 CA_FIRM_NAME_1='".$row['CA_FIRM_NAME_1']."',
			 CAPACITY_CONNECTED_1='".$CAPACITY_CONNECTED_1."',
			 OCCUPATION_DETAILS_1='".$row['OCCUPATION_DETAILS_1']."',
			 PAR_PRO_PA_NAME_2='".$row['PAR_PRO_PA_NAME_2']."',
			 CA_FIRM_NAME_2='".$CA_FIRM_NAME_2."',
			 
			 
			 CAPACITY_CONNECTED_2='".$row['CAPACITY_CONNECTED_2']."',
			 OCCUPATION_DETAILS_2='".$OCCUPATION_DETAILS_2."', 
			 PAR_PRO_PA_NAME_3='".$row['PAR_PRO_PA_NAME_3']."', 
			 CA_FIRM_NAME_3='".$row['CA_FIRM_NAME_3']."',
			 CAPACITY_CONNECTED_3='".$row['CAPACITY_CONNECTED_3']."',

			 OCCUPATION_DETAILS_3='".$row['OCCUPATION_DETAILS_3']."',
			 FIRM_IND_PAR_NAME='".$row['FIRM_IND_PAR_NAME']."', 
			
			 
			 FIRM_MEMBERSHIP_NUMBER_LINE_1='".$row['FIRM_MEMBERSHIP_NUMBER_LINE_1']."', 
			 FIRM_MEM_NAME_LINE_2='".$row['FIRM_MEM_NAME_LINE_2']."',
			 FIRM_MEMBERSHIP_NUMBER_LINE_2='".$row['FIRM_MEMBERSHIP_NUMBER_LINE_2']."', 
			 FIRM_MEM_NAME_LINE_3='".$row['FIRM_MEM_NAME_LINE_3']."',
			 FIRM_MEMBERSHIP_NUMBER_LINE_3='".$row['FIRM_MEMBERSHIP_NUMBER_LINE_3']."',
			 FIRM_MEM_NAME_LINE_4='".$row['FIRM_MEM_NAME_LINE_4']."',
			 FIRM_MEMBERSHIP_NUMBER_LINE_4='".$row['FIRM_MEMBERSHIP_NUMBER_LINE_4']."',
			 FIRM_MEM_NAME_LINE_5='".$row['FIRM_MEM_NAME_LINE_5']."',
			 
			 FIRM_MEMBERSHIP_NUMBER_LINE_5='".$row['FIRM_MEMBERSHIP_NUMBER_LINE_5']."',
			 INS_MEM_NAME_LINE_1='".$row['INS_MEM_NAME_LINE_1']."',
			 
			 
			 
			 INS_MEM_NUMBER_LINE_1='".$row['INS_MEM_NUMBER_LINE_1']."',
			 INS_MEM_DOJ_LINE_1='".$INS_MEM_DOJ_LINE_1."', 
			 
			 INS_MEM_NAME_LINE_2='".$INS_MEM_NAME_LINE_2."',
			 INS_MEM_NUMBER_LINE_2='".$row['INS_MEM_NUMBER_LINE_2']."',
			 INS_MEM_DOJ_LINE_2='".$INS_MEM_DOJ_LINE_2."', 
			 INS_MEM_NAME_LINE_3='".$row['INS_MEM_NAME_LINE_3']."',
			 
			 
			 
			 INS_MEM_NUMBER_LINE_3='".$row['INS_MEM_NUMBER_LINE_3']."', 
			 INS_MEM_DOJ_LINE_3='".$INS_MEM_DOJ_LINE_3."',
			 INS_MEM_NAME_LINE_4='".$row['INS_MEM_NAME_LINE_4']."', 
			 INS_MEM_NUMBER_LINE_4='".$row['INS_MEM_NUMBER_LINE_4']."',
			 INS_MEM_DOJ_LINE_4='".$INS_MEM_DOJ_LINE_4."',
			 INS_MEM_NAME_LINE_5='".$row['INS_MEM_NAME_LINE_5']."',
			 INS_MEM_NUMBER_LINE_5='".$row['INS_MEM_NUMBER_LINE_5']."',
			 INS_MEM_DOJ_LINE_5='".$INS_MEM_DOJ_LINE_5."',
			 
			 PAID_ASSISTANT='".$row['PAID_ASSISTANT']."',
			 PAID_ASSISTANCE_NAME_LINE_1='".$row['PAID_ASSISTANCE_NAME_LINE_1']."', 
			 ENGAGED_PAR_PRO_PA_NAME_LINE_1='".$row['ENGAGED_PAR_PRO_PA_NAME_LINE_1']."',
			 ENGAGED_CAP_CONN_LINE_1='".$row['ENGAGED_CAP_CONN_LINE_1']."',
			 PAID_ASSISTANCE_NAME_LINE_2='".$row['PAID_ASSISTANCE_NAME_LINE_2']."',
			 ENGAGED_PAR_PRO_PA_NAME_LINE_2='".$row['ENGAGED_PAR_PRO_PA_NAME_LINE_2']."',
			 ENGAGED_CAP_CONN_LINE_2='".$row['ENGAGED_CAP_CONN_LINE_2']."',
			 
			 
			 PAID_ASSISTANCE_NAME_LINE_3='".$row['PAID_ASSISTANCE_NAME_LINE_3']."', 
			 ENGAGED_PAR_PRO_PA_NAME_LINE_3='".$row['ENGAGED_PAR_PRO_PA_NAME_LINE_3']."',
			 ENGAGED_CAP_CONN_LINE_3='".$row['ENGAGED_CAP_CONN_LINE_3']."',
			 PAID_ASSISTANCE_STATUS='".$row['PAID_ASSISTANCE_STATUS']."',
			 INDIVISUAL_PA_NAME_LINE_1='".$row['INDIVISUAL_PA_NAME_LINE_1']."',
			 INDIVISUAL_PA_MEM_NO_LINE_1='".$row['INDIVISUAL_PA_MEM_NO_LINE_1']."',
			 
			 INDIVISUAL_PA_NAME_LINE_2='".$row['INDIVISUAL_PA_NAME_LINE_2']."', 
			 INDIVISUAL_PA_MEM_NO_LINE_2='".$row['INDIVISUAL_PA_MEM_NO_LINE_2']."',
			 INDIVISUAL_PA_NAME_LINE_3='".$row['INDIVISUAL_PA_NAME_LINE_3']."',
			 INDIVISUAL_PA_MEM_NO_LINE_3='".$row['INDIVISUAL_PA_MEM_NO_LINE_3']."',
			 
			 
			 INDIVISUAL_PA_NAME_LINE_4='".$row['INDIVISUAL_PA_NAME_LINE_4']."', 
			 INDIVISUAL_PA_MEM_NO_LINE_4='".$row['INDIVISUAL_PA_MEM_NO_LINE_4']."',
			 INDIVISUAL_PA_MEM_DATE='".$INDIVISUAL_PA_MEM_DATE."',
			 INDIVISUAL_PA_MEM_PLACE='".$row['INDIVISUAL_PA_MEM_PLACE']."',
			 
			 
			 SIGNATURE_MM_NUMBER_1='".$row['SIGNATURE_MM_NUMBER_1']."', 
			 SIGNATURE_MM_NUMBER_2='".$row['SIGNATURE_MM_NUMBER_2']."',
			 SIGNATURE_MM_NUMBER_3='".$row['SIGNATURE_MM_NUMBER_3']."',
			 SIGNATURE_MM_NUMBER_4='".$row['SIGNATURE_MM_NUMBER_4']."',
			 SIGNATURE_MM_NUMBER_5='".$row['SIGNATURE_MM_NUMBER_5']."',
			 SIGNATURE_MM_NUMBER_6='".$row['SIGNATURE_MM_NUMBER_6']."',
			 
			 
			 MRH_MRN='".$row['MRH_MRN']."', 
			 TRADE_NAME='".$row['TRADE_NAME']."',
			 FORM_SAVE_STATUS='".$row['FORM_SAVE_STATUS']."',
			 FORM_SUBMIT_DT='".$FORM_SUBMIT_DT."',
			 User_IP='".$row['User_IP']."',
			 NAME_RESTORING_CONTROL_NO='".$row['NAME_RESTORING_CONTROL_NO']."' ,
			 
			 
			 STUD_REGION_CODE='".$row['STUD_REGION_CODE']."' ,
			 TOTAL_AMT='".$row['TOTAL_AMT']."' ,
			 MRH_TRANS_DATE='".$row['MRH_TRANS_DATE']."' ,
			 MRH_TRANS_ID='".$row['MRH_TRANS_ID']."' ,
			 MRH_TRANS_RESPONSE='".$row['MRH_TRANS_RESPONSE']."' ,
			 MRH_TRANS_STATUS='".$row['MRH_TRANS_STATUS']."' ,
			 
			 
			 MRH_PDF_PATH='".$row['MRH_PDF_PATH']."' ,
			 MRH_TRANS_TOTAL_AMT='".$row['MRH_TRANS_TOTAL_AMT']."' ,
			 STUD_SYS_ID='".$row['STUD_SYS_ID']."' ,
			 Get_BY_DS='".$row['Get_BY_DS']."' ,
			 Get_BY_DS_date='".$Get_BY_DS_date."',
			 Post_BY_Cloud='".$row['Post_BY_Cloud']."' ,
			 
			 Post_BY_Cloud_date=now(),
			 STUD_PART1_MEMBER_NO='".$row['STUD_PART1_MEMBER_NO']."' ,
			 MRH_CONSTITUTION_FORM='".$row['MRH_CONSTITUTION_FORM']."' ,
			 
			 
			 DELAY_FEE='".$row['DELAY_FEE']."' ";
			 //echo $sql2;die;
			 $stmt2 = $conn4->prepare($sql2);
			  
            $stmt2->execute();
			$form_number = 'form_18';
			  get_transfer_form_restore($form_username, $form_number, $FORM_NO);
			  //$MRH_MRN,$form_number, $FORM_NO
			  }			  
          }		  
		
	  
		}else{
			
			echo "NO connection with delhi server";
		}	  
}


/********************************************************/

/*********************** ADD PDF PATH END ***************/



/* function get_cityName_18($city_code){	 
    global $conn2; 
			
	$result4 = $conn2->query("SET NAMES utf8");
	$stmt = $conn2->prepare("SELECT city_name FROM om_city WHERE city_code = ?  ");	
	$stmt->bindValue(1, $city_code);
	$stmt->execute();
	$result4=$stmt->fetchAll();
	if (count($result4) > 0){		
		$city_name= $result4[0]['city_name'];	
		return $city_name;		  
	}	 
}
function dd_mm_yyyy_18($date){
	if($date != '' && $date != '0000-00-00'){
		$newDate = date("d-m-Y", strtotime($date));
		return $newDate;
	}
	
} */
?>
